// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adminactionlog"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AdminActionLogUpdate is the builder for updating AdminActionLog entities.
type AdminActionLogUpdate struct {
	config
	hooks    []Hook
	mutation *AdminActionLogMutation
}

// Where appends a list predicates to the AdminActionLogUpdate builder.
func (_u *AdminActionLogUpdate) Where(ps ...predicate.AdminActionLog) *AdminActionLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAdminID sets the "admin_id" field.
func (_u *AdminActionLogUpdate) SetAdminID(v int64) *AdminActionLogUpdate {
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *AdminActionLogUpdate) SetNillableAdminID(v *int64) *AdminActionLogUpdate {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// ClearAdminID clears the value of the "admin_id" field.
func (_u *AdminActionLogUpdate) ClearAdminID() *AdminActionLogUpdate {
	_u.mutation.ClearAdminID()
	return _u
}

// SetAction sets the "action" field.
func (_u *AdminActionLogUpdate) SetAction(v string) *AdminActionLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AdminActionLogUpdate) SetNillableAction(v *string) *AdminActionLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *AdminActionLogUpdate) SetResourceType(v string) *AdminActionLogUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *AdminActionLogUpdate) SetNillableResourceType(v *string) *AdminActionLogUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *AdminActionLogUpdate) SetResourceID(v int64) *AdminActionLogUpdate {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *AdminActionLogUpdate) SetNillableResourceID(v *int64) *AdminActionLogUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *AdminActionLogUpdate) AddResourceID(v int64) *AdminActionLogUpdate {
	_u.mutation.AddResourceID(v)
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *AdminActionLogUpdate) ClearResourceID() *AdminActionLogUpdate {
	_u.mutation.ClearResourceID()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *AdminActionLogUpdate) SetPayload(v string) *AdminActionLogUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *AdminActionLogUpdate) SetNillablePayload(v *string) *AdminActionLogUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *AdminActionLogUpdate) ClearPayload() *AdminActionLogUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *AdminActionLogUpdate) SetIPAddress(v string) *AdminActionLogUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *AdminActionLogUpdate) SetNillableIPAddress(v *string) *AdminActionLogUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *AdminActionLogUpdate) ClearIPAddress() *AdminActionLogUpdate {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *AdminActionLogUpdate) SetUserAgent(v string) *AdminActionLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *AdminActionLogUpdate) SetNillableUserAgent(v *string) *AdminActionLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *AdminActionLogUpdate) ClearUserAgent() *AdminActionLogUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AdminActionLogUpdate) SetCreatedAt(v time.Time) *AdminActionLogUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AdminActionLogUpdate) SetNillableCreatedAt(v *time.Time) *AdminActionLogUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetAdmin sets the "admin" edge to the User entity.
func (_u *AdminActionLogUpdate) SetAdmin(v *User) *AdminActionLogUpdate {
	return _u.SetAdminID(v.ID)
}

// Mutation returns the AdminActionLogMutation object of the builder.
func (_u *AdminActionLogUpdate) Mutation() *AdminActionLogMutation {
	return _u.mutation
}

// ClearAdmin clears the "admin" edge to the User entity.
func (_u *AdminActionLogUpdate) ClearAdmin() *AdminActionLogUpdate {
	_u.mutation.ClearAdmin()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminActionLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminActionLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminActionLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminActionLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminActionLogUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := adminactionlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AdminActionLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := adminactionlog.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "AdminActionLog.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := adminactionlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "AdminActionLog.ip_address": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminActionLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminactionlog.Table, adminactionlog.Columns, sqlgraph.NewFieldSpec(adminactionlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(adminactionlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(adminactionlog.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(adminactionlog.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(adminactionlog.FieldResourceID, field.TypeInt64, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(adminactionlog.FieldResourceID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(adminactionlog.FieldPayload, field.TypeString, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(adminactionlog.FieldPayload, field.TypeString)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(adminactionlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(adminactionlog.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(adminactionlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(adminactionlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(adminactionlog.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.AdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminactionlog.AdminTable,
			Columns: []string{adminactionlog.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminactionlog.AdminTable,
			Columns: []string{adminactionlog.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminactionlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminActionLogUpdateOne is the builder for updating a single AdminActionLog entity.
type AdminActionLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminActionLogMutation
}

// SetAdminID sets the "admin_id" field.
func (_u *AdminActionLogUpdateOne) SetAdminID(v int64) *AdminActionLogUpdateOne {
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *AdminActionLogUpdateOne) SetNillableAdminID(v *int64) *AdminActionLogUpdateOne {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// ClearAdminID clears the value of the "admin_id" field.
func (_u *AdminActionLogUpdateOne) ClearAdminID() *AdminActionLogUpdateOne {
	_u.mutation.ClearAdminID()
	return _u
}

// SetAction sets the "action" field.
func (_u *AdminActionLogUpdateOne) SetAction(v string) *AdminActionLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AdminActionLogUpdateOne) SetNillableAction(v *string) *AdminActionLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *AdminActionLogUpdateOne) SetResourceType(v string) *AdminActionLogUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *AdminActionLogUpdateOne) SetNillableResourceType(v *string) *AdminActionLogUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *AdminActionLogUpdateOne) SetResourceID(v int64) *AdminActionLogUpdateOne {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *AdminActionLogUpdateOne) SetNillableResourceID(v *int64) *AdminActionLogUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *AdminActionLogUpdateOne) AddResourceID(v int64) *AdminActionLogUpdateOne {
	_u.mutation.AddResourceID(v)
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *AdminActionLogUpdateOne) ClearResourceID() *AdminActionLogUpdateOne {
	_u.mutation.ClearResourceID()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *AdminActionLogUpdateOne) SetPayload(v string) *AdminActionLogUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *AdminActionLogUpdateOne) SetNillablePayload(v *string) *AdminActionLogUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *AdminActionLogUpdateOne) ClearPayload() *AdminActionLogUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *AdminActionLogUpdateOne) SetIPAddress(v string) *AdminActionLogUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *AdminActionLogUpdateOne) SetNillableIPAddress(v *string) *AdminActionLogUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *AdminActionLogUpdateOne) ClearIPAddress() *AdminActionLogUpdateOne {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *AdminActionLogUpdateOne) SetUserAgent(v string) *AdminActionLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *AdminActionLogUpdateOne) SetNillableUserAgent(v *string) *AdminActionLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *AdminActionLogUpdateOne) ClearUserAgent() *AdminActionLogUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AdminActionLogUpdateOne) SetCreatedAt(v time.Time) *AdminActionLogUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AdminActionLogUpdateOne) SetNillableCreatedAt(v *time.Time) *AdminActionLogUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetAdmin sets the "admin" edge to the User entity.
func (_u *AdminActionLogUpdateOne) SetAdmin(v *User) *AdminActionLogUpdateOne {
	return _u.SetAdminID(v.ID)
}

// Mutation returns the AdminActionLogMutation object of the builder.
func (_u *AdminActionLogUpdateOne) Mutation() *AdminActionLogMutation {
	return _u.mutation
}

// ClearAdmin clears the "admin" edge to the User entity.
func (_u *AdminActionLogUpdateOne) ClearAdmin() *AdminActionLogUpdateOne {
	_u.mutation.ClearAdmin()
	return _u
}

// Where appends a list predicates to the AdminActionLogUpdate builder.
func (_u *AdminActionLogUpdateOne) Where(ps ...predicate.AdminActionLog) *AdminActionLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminActionLogUpdateOne) Select(field string, fields ...string) *AdminActionLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminActionLog entity.
func (_u *AdminActionLogUpdateOne) Save(ctx context.Context) (*AdminActionLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminActionLogUpdateOne) SaveX(ctx context.Context) *AdminActionLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminActionLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminActionLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminActionLogUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := adminactionlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AdminActionLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := adminactionlog.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "AdminActionLog.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := adminactionlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "AdminActionLog.ip_address": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminActionLogUpdateOne) sqlSave(ctx context.Context) (_node *AdminActionLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminactionlog.Table, adminactionlog.Columns, sqlgraph.NewFieldSpec(adminactionlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminActionLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminactionlog.FieldID)
		for _, f := range fields {
			if !adminactionlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminactionlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(adminactionlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(adminactionlog.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(adminactionlog.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(adminactionlog.FieldResourceID, field.TypeInt64, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(adminactionlog.FieldResourceID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(adminactionlog.FieldPayload, field.TypeString, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(adminactionlog.FieldPayload, field.TypeString)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(adminactionlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(adminactionlog.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(adminactionlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(adminactionlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(adminactionlog.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.AdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminactionlog.AdminTable,
			Columns: []string{adminactionlog.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminactionlog.AdminTable,
			Columns: []string{adminactionlog.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AdminActionLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminactionlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
