// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/adminactionlog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AdminActionLog is the model entity for the AdminActionLog schema.
type AdminActionLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AdminID holds the value of the "admin_id" field.
	AdminID *int64 `json:"admin_id,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// ResourceType holds the value of the "resource_type" field.
	ResourceType string `json:"resource_type,omitempty"`
	// ResourceID holds the value of the "resource_id" field.
	ResourceID *int64 `json:"resource_id,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload *string `json:"payload,omitempty"`
	// IPAddress holds the value of the "ip_address" field.
	IPAddress *string `json:"ip_address,omitempty"`
	// UserAgent holds the value of the "user_agent" field.
	UserAgent *string `json:"user_agent,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdminActionLogQuery when eager-loading is set.
	Edges        AdminActionLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AdminActionLogEdges holds the relations/edges for other nodes in the graph.
type AdminActionLogEdges struct {
	// Admin holds the value of the admin edge.
	Admin *User `json:"admin,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AdminOrErr returns the Admin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdminActionLogEdges) AdminOrErr() (*User, error) {
	if e.Admin != nil {
		return e.Admin, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "admin"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdminActionLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adminactionlog.FieldID, adminactionlog.FieldAdminID, adminactionlog.FieldResourceID:
			values[i] = new(sql.NullInt64)
		case adminactionlog.FieldAction, adminactionlog.FieldResourceType, adminactionlog.FieldPayload, adminactionlog.FieldIPAddress, adminactionlog.FieldUserAgent:
			values[i] = new(sql.NullString)
		case adminactionlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdminActionLog fields.
func (_m *AdminActionLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adminactionlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case adminactionlog.FieldAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field admin_id", values[i])
			} else if value.Valid {
				_m.AdminID = new(int64)
				*_m.AdminID = value.Int64
			}
		case adminactionlog.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case adminactionlog.FieldResourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_type", values[i])
			} else if value.Valid {
				_m.ResourceType = value.String
			}
		case adminactionlog.FieldResourceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value.Valid {
				_m.ResourceID = new(int64)
				*_m.ResourceID = value.Int64
			}
		case adminactionlog.FieldPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value.Valid {
				_m.Payload = new(string)
				*_m.Payload = value.String
			}
		case adminactionlog.FieldIPAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_address", values[i])
			} else if value.Valid {
				_m.IPAddress = new(string)
				*_m.IPAddress = value.String
			}
		case adminactionlog.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = new(string)
				*_m.UserAgent = value.String
			}
		case adminactionlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdminActionLog.
// This includes values selected through modifiers, order, etc.
func (_m *AdminActionLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAdmin queries the "admin" edge of the AdminActionLog entity.
func (_m *AdminActionLog) QueryAdmin() *UserQuery {
	return NewAdminActionLogClient(_m.config).QueryAdmin(_m)
}

// Update returns a builder for updating this AdminActionLog.
// Note that you need to call AdminActionLog.Unwrap() before calling this method if this AdminActionLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AdminActionLog) Update() *AdminActionLogUpdateOne {
	return NewAdminActionLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AdminActionLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AdminActionLog) Unwrap() *AdminActionLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdminActionLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AdminActionLog) String() string {
	var builder strings.Builder
	builder.WriteString("AdminActionLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.AdminID; v != nil {
		builder.WriteString("admin_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("resource_type=")
	builder.WriteString(_m.ResourceType)
	builder.WriteString(", ")
	if v := _m.ResourceID; v != nil {
		builder.WriteString("resource_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Payload; v != nil {
		builder.WriteString("payload=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IPAddress; v != nil {
		builder.WriteString("ip_address=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UserAgent; v != nil {
		builder.WriteString("user_agent=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AdminActionLogs is a parsable slice of AdminActionLog.
type AdminActionLogs []*AdminActionLog
