// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adminactionlog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AdminActionLogCreate is the builder for creating a AdminActionLog entity.
type AdminActionLogCreate struct {
	config
	mutation *AdminActionLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAdminID sets the "admin_id" field.
func (_c *AdminActionLogCreate) SetAdminID(v int64) *AdminActionLogCreate {
	_c.mutation.SetAdminID(v)
	return _c
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_c *AdminActionLogCreate) SetNillableAdminID(v *int64) *AdminActionLogCreate {
	if v != nil {
		_c.SetAdminID(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *AdminActionLogCreate) SetAction(v string) *AdminActionLogCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *AdminActionLogCreate) SetResourceType(v string) *AdminActionLogCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *AdminActionLogCreate) SetResourceID(v int64) *AdminActionLogCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_c *AdminActionLogCreate) SetNillableResourceID(v *int64) *AdminActionLogCreate {
	if v != nil {
		_c.SetResourceID(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *AdminActionLogCreate) SetPayload(v string) *AdminActionLogCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_c *AdminActionLogCreate) SetNillablePayload(v *string) *AdminActionLogCreate {
	if v != nil {
		_c.SetPayload(*v)
	}
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *AdminActionLogCreate) SetIPAddress(v string) *AdminActionLogCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_c *AdminActionLogCreate) SetNillableIPAddress(v *string) *AdminActionLogCreate {
	if v != nil {
		_c.SetIPAddress(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *AdminActionLogCreate) SetUserAgent(v string) *AdminActionLogCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *AdminActionLogCreate) SetNillableUserAgent(v *string) *AdminActionLogCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdminActionLogCreate) SetCreatedAt(v time.Time) *AdminActionLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdminActionLogCreate) SetNillableCreatedAt(v *time.Time) *AdminActionLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAdmin sets the "admin" edge to the User entity.
func (_c *AdminActionLogCreate) SetAdmin(v *User) *AdminActionLogCreate {
	return _c.SetAdminID(v.ID)
}

// Mutation returns the AdminActionLogMutation object of the builder.
func (_c *AdminActionLogCreate) Mutation() *AdminActionLogMutation {
	return _c.mutation
}

// Save creates the AdminActionLog in the database.
func (_c *AdminActionLogCreate) Save(ctx context.Context) (*AdminActionLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdminActionLogCreate) SaveX(ctx context.Context) *AdminActionLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminActionLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminActionLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdminActionLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := adminactionlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdminActionLogCreate) check() error {
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "AdminActionLog.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := adminactionlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AdminActionLog.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "AdminActionLog.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := adminactionlog.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "AdminActionLog.resource_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := adminactionlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "AdminActionLog.ip_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdminActionLog.created_at"`)}
	}
	return nil
}

func (_c *AdminActionLogCreate) sqlSave(ctx context.Context) (*AdminActionLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdminActionLogCreate) createSpec() (*AdminActionLog, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminActionLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adminactionlog.Table, sqlgraph.NewFieldSpec(adminactionlog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(adminactionlog.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(adminactionlog.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(adminactionlog.FieldResourceID, field.TypeInt64, value)
		_node.ResourceID = &value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(adminactionlog.FieldPayload, field.TypeString, value)
		_node.Payload = &value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(adminactionlog.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = &value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(adminactionlog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adminactionlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.AdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminactionlog.AdminTable,
			Columns: []string{adminactionlog.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AdminID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdminActionLog.Create().
//		SetAdminID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdminActionLogUpsert) {
//			SetAdminID(v+v).
//		}).
//		Exec(ctx)
func (_c *AdminActionLogCreate) OnConflict(opts ...sql.ConflictOption) *AdminActionLogUpsertOne {
	_c.conflict = opts
	return &AdminActionLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdminActionLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdminActionLogCreate) OnConflictColumns(columns ...string) *AdminActionLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdminActionLogUpsertOne{
		create: _c,
	}
}

type (
	// AdminActionLogUpsertOne is the builder for "upsert"-ing
	//  one AdminActionLog node.
	AdminActionLogUpsertOne struct {
		create *AdminActionLogCreate
	}

	// AdminActionLogUpsert is the "OnConflict" setter.
	AdminActionLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetAdminID sets the "admin_id" field.
func (u *AdminActionLogUpsert) SetAdminID(v int64) *AdminActionLogUpsert {
	u.Set(adminactionlog.FieldAdminID, v)
	return u
}

// UpdateAdminID sets the "admin_id" field to the value that was provided on create.
func (u *AdminActionLogUpsert) UpdateAdminID() *AdminActionLogUpsert {
	u.SetExcluded(adminactionlog.FieldAdminID)
	return u
}

// ClearAdminID clears the value of the "admin_id" field.
func (u *AdminActionLogUpsert) ClearAdminID() *AdminActionLogUpsert {
	u.SetNull(adminactionlog.FieldAdminID)
	return u
}

// SetAction sets the "action" field.
func (u *AdminActionLogUpsert) SetAction(v string) *AdminActionLogUpsert {
	u.Set(adminactionlog.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *AdminActionLogUpsert) UpdateAction() *AdminActionLogUpsert {
	u.SetExcluded(adminactionlog.FieldAction)
	return u
}

// SetResourceType sets the "resource_type" field.
func (u *AdminActionLogUpsert) SetResourceType(v string) *AdminActionLogUpsert {
	u.Set(adminactionlog.FieldResourceType, v)
	return u
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *AdminActionLogUpsert) UpdateResourceType() *AdminActionLogUpsert {
	u.SetExcluded(adminactionlog.FieldResourceType)
	return u
}

// SetResourceID sets the "resource_id" field.
func (u *AdminActionLogUpsert) SetResourceID(v int64) *AdminActionLogUpsert {
	u.Set(adminactionlog.FieldResourceID, v)
	return u
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *AdminActionLogUpsert) UpdateResourceID() *AdminActionLogUpsert {
	u.SetExcluded(adminactionlog.FieldResourceID)
	return u
}

// AddResourceID adds v to the "resource_id" field.
func (u *AdminActionLogUpsert) AddResourceID(v int64) *AdminActionLogUpsert {
	u.Add(adminactionlog.FieldResourceID, v)
	return u
}

// ClearResourceID clears the value of the "resource_id" field.
func (u *AdminActionLogUpsert) ClearResourceID() *AdminActionLogUpsert {
	u.SetNull(adminactionlog.FieldResourceID)
	return u
}

// SetPayload sets the "payload" field.
func (u *AdminActionLogUpsert) SetPayload(v string) *AdminActionLogUpsert {
	u.Set(adminactionlog.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *AdminActionLogUpsert) UpdatePayload() *AdminActionLogUpsert {
	u.SetExcluded(adminactionlog.FieldPayload)
	return u
}

// ClearPayload clears the value of the "payload" field.
func (u *AdminActionLogUpsert) ClearPayload() *AdminActionLogUpsert {
	u.SetNull(adminactionlog.FieldPayload)
	return u
}

// SetIPAddress sets the "ip_address" field.
func (u *AdminActionLogUpsert) SetIPAddress(v string) *AdminActionLogUpsert {
	u.Set(adminactionlog.FieldIPAddress, v)
	return u
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *AdminActionLogUpsert) UpdateIPAddress() *AdminActionLogUpsert {
	u.SetExcluded(adminactionlog.FieldIPAddress)
	return u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *AdminActionLogUpsert) ClearIPAddress() *AdminActionLogUpsert {
	u.SetNull(adminactionlog.FieldIPAddress)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *AdminActionLogUpsert) SetUserAgent(v string) *AdminActionLogUpsert {
	u.Set(adminactionlog.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *AdminActionLogUpsert) UpdateUserAgent() *AdminActionLogUpsert {
	u.SetExcluded(adminactionlog.FieldUserAgent)
	return u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *AdminActionLogUpsert) ClearUserAgent() *AdminActionLogUpsert {
	u.SetNull(adminactionlog.FieldUserAgent)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *AdminActionLogUpsert) SetCreatedAt(v time.Time) *AdminActionLogUpsert {
	u.Set(adminactionlog.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AdminActionLogUpsert) UpdateCreatedAt() *AdminActionLogUpsert {
	u.SetExcluded(adminactionlog.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AdminActionLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdminActionLogUpsertOne) UpdateNewValues() *AdminActionLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdminActionLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AdminActionLogUpsertOne) Ignore() *AdminActionLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdminActionLogUpsertOne) DoNothing() *AdminActionLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdminActionLogCreate.OnConflict
// documentation for more info.
func (u *AdminActionLogUpsertOne) Update(set func(*AdminActionLogUpsert)) *AdminActionLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdminActionLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetAdminID sets the "admin_id" field.
func (u *AdminActionLogUpsertOne) SetAdminID(v int64) *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.SetAdminID(v)
	})
}

// UpdateAdminID sets the "admin_id" field to the value that was provided on create.
func (u *AdminActionLogUpsertOne) UpdateAdminID() *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.UpdateAdminID()
	})
}

// ClearAdminID clears the value of the "admin_id" field.
func (u *AdminActionLogUpsertOne) ClearAdminID() *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.ClearAdminID()
	})
}

// SetAction sets the "action" field.
func (u *AdminActionLogUpsertOne) SetAction(v string) *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *AdminActionLogUpsertOne) UpdateAction() *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.UpdateAction()
	})
}

// SetResourceType sets the "resource_type" field.
func (u *AdminActionLogUpsertOne) SetResourceType(v string) *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.SetResourceType(v)
	})
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *AdminActionLogUpsertOne) UpdateResourceType() *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.UpdateResourceType()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *AdminActionLogUpsertOne) SetResourceID(v int64) *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.SetResourceID(v)
	})
}

// AddResourceID adds v to the "resource_id" field.
func (u *AdminActionLogUpsertOne) AddResourceID(v int64) *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.AddResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *AdminActionLogUpsertOne) UpdateResourceID() *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.UpdateResourceID()
	})
}

// ClearResourceID clears the value of the "resource_id" field.
func (u *AdminActionLogUpsertOne) ClearResourceID() *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.ClearResourceID()
	})
}

// SetPayload sets the "payload" field.
func (u *AdminActionLogUpsertOne) SetPayload(v string) *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *AdminActionLogUpsertOne) UpdatePayload() *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.UpdatePayload()
	})
}

// ClearPayload clears the value of the "payload" field.
func (u *AdminActionLogUpsertOne) ClearPayload() *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.ClearPayload()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *AdminActionLogUpsertOne) SetIPAddress(v string) *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *AdminActionLogUpsertOne) UpdateIPAddress() *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.UpdateIPAddress()
	})
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *AdminActionLogUpsertOne) ClearIPAddress() *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.ClearIPAddress()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *AdminActionLogUpsertOne) SetUserAgent(v string) *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *AdminActionLogUpsertOne) UpdateUserAgent() *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *AdminActionLogUpsertOne) ClearUserAgent() *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.ClearUserAgent()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *AdminActionLogUpsertOne) SetCreatedAt(v time.Time) *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AdminActionLogUpsertOne) UpdateCreatedAt() *AdminActionLogUpsertOne {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *AdminActionLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdminActionLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdminActionLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AdminActionLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AdminActionLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AdminActionLogCreateBulk is the builder for creating many AdminActionLog entities in bulk.
type AdminActionLogCreateBulk struct {
	config
	err      error
	builders []*AdminActionLogCreate
	conflict []sql.ConflictOption
}

// Save creates the AdminActionLog entities in the database.
func (_c *AdminActionLogCreateBulk) Save(ctx context.Context) ([]*AdminActionLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdminActionLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminActionLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdminActionLogCreateBulk) SaveX(ctx context.Context) []*AdminActionLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminActionLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminActionLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdminActionLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdminActionLogUpsert) {
//			SetAdminID(v+v).
//		}).
//		Exec(ctx)
func (_c *AdminActionLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *AdminActionLogUpsertBulk {
	_c.conflict = opts
	return &AdminActionLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdminActionLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdminActionLogCreateBulk) OnConflictColumns(columns ...string) *AdminActionLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdminActionLogUpsertBulk{
		create: _c,
	}
}

// AdminActionLogUpsertBulk is the builder for "upsert"-ing
// a bulk of AdminActionLog nodes.
type AdminActionLogUpsertBulk struct {
	create *AdminActionLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AdminActionLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdminActionLogUpsertBulk) UpdateNewValues() *AdminActionLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdminActionLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AdminActionLogUpsertBulk) Ignore() *AdminActionLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdminActionLogUpsertBulk) DoNothing() *AdminActionLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdminActionLogCreateBulk.OnConflict
// documentation for more info.
func (u *AdminActionLogUpsertBulk) Update(set func(*AdminActionLogUpsert)) *AdminActionLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdminActionLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetAdminID sets the "admin_id" field.
func (u *AdminActionLogUpsertBulk) SetAdminID(v int64) *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.SetAdminID(v)
	})
}

// UpdateAdminID sets the "admin_id" field to the value that was provided on create.
func (u *AdminActionLogUpsertBulk) UpdateAdminID() *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.UpdateAdminID()
	})
}

// ClearAdminID clears the value of the "admin_id" field.
func (u *AdminActionLogUpsertBulk) ClearAdminID() *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.ClearAdminID()
	})
}

// SetAction sets the "action" field.
func (u *AdminActionLogUpsertBulk) SetAction(v string) *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *AdminActionLogUpsertBulk) UpdateAction() *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.UpdateAction()
	})
}

// SetResourceType sets the "resource_type" field.
func (u *AdminActionLogUpsertBulk) SetResourceType(v string) *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.SetResourceType(v)
	})
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *AdminActionLogUpsertBulk) UpdateResourceType() *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.UpdateResourceType()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *AdminActionLogUpsertBulk) SetResourceID(v int64) *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.SetResourceID(v)
	})
}

// AddResourceID adds v to the "resource_id" field.
func (u *AdminActionLogUpsertBulk) AddResourceID(v int64) *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.AddResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *AdminActionLogUpsertBulk) UpdateResourceID() *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.UpdateResourceID()
	})
}

// ClearResourceID clears the value of the "resource_id" field.
func (u *AdminActionLogUpsertBulk) ClearResourceID() *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.ClearResourceID()
	})
}

// SetPayload sets the "payload" field.
func (u *AdminActionLogUpsertBulk) SetPayload(v string) *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *AdminActionLogUpsertBulk) UpdatePayload() *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.UpdatePayload()
	})
}

// ClearPayload clears the value of the "payload" field.
func (u *AdminActionLogUpsertBulk) ClearPayload() *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.ClearPayload()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *AdminActionLogUpsertBulk) SetIPAddress(v string) *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *AdminActionLogUpsertBulk) UpdateIPAddress() *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.UpdateIPAddress()
	})
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *AdminActionLogUpsertBulk) ClearIPAddress() *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.ClearIPAddress()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *AdminActionLogUpsertBulk) SetUserAgent(v string) *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *AdminActionLogUpsertBulk) UpdateUserAgent() *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *AdminActionLogUpsertBulk) ClearUserAgent() *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.ClearUserAgent()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *AdminActionLogUpsertBulk) SetCreatedAt(v time.Time) *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AdminActionLogUpsertBulk) UpdateCreatedAt() *AdminActionLogUpsertBulk {
	return u.Update(func(s *AdminActionLogUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *AdminActionLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AdminActionLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdminActionLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdminActionLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
