// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invitation"
	"github.com/Wei-Shaw/sub2api/ent/invitelog"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvitationUpdate is the builder for updating Invitation entities.
type InvitationUpdate struct {
	config
	hooks    []Hook
	mutation *InvitationMutation
}

// Where appends a list predicates to the InvitationUpdate builder.
func (_u *InvitationUpdate) Where(ps ...predicate.Invitation) *InvitationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInviterID sets the "inviter_id" field.
func (_u *InvitationUpdate) SetInviterID(v int64) *InvitationUpdate {
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableInviterID(v *int64) *InvitationUpdate {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// SetInviteeID sets the "invitee_id" field.
func (_u *InvitationUpdate) SetInviteeID(v int64) *InvitationUpdate {
	_u.mutation.SetInviteeID(v)
	return _u
}

// SetNillableInviteeID sets the "invitee_id" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableInviteeID(v *int64) *InvitationUpdate {
	if v != nil {
		_u.SetInviteeID(*v)
	}
	return _u
}

// SetInviteCode sets the "invite_code" field.
func (_u *InvitationUpdate) SetInviteCode(v string) *InvitationUpdate {
	_u.mutation.SetInviteCode(v)
	return _u
}

// SetNillableInviteCode sets the "invite_code" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableInviteCode(v *string) *InvitationUpdate {
	if v != nil {
		_u.SetInviteCode(*v)
	}
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *InvitationUpdate) SetRewardAmount(v float64) *InvitationUpdate {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableRewardAmount(v *float64) *InvitationUpdate {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *InvitationUpdate) AddRewardAmount(v float64) *InvitationUpdate {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvitationUpdate) SetStatus(v string) *InvitationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableStatus(v *string) *InvitationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConfirmedBy sets the "confirmed_by" field.
func (_u *InvitationUpdate) SetConfirmedBy(v int64) *InvitationUpdate {
	_u.mutation.SetConfirmedBy(v)
	return _u
}

// SetNillableConfirmedBy sets the "confirmed_by" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableConfirmedBy(v *int64) *InvitationUpdate {
	if v != nil {
		_u.SetConfirmedBy(*v)
	}
	return _u
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (_u *InvitationUpdate) ClearConfirmedBy() *InvitationUpdate {
	_u.mutation.ClearConfirmedBy()
	return _u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_u *InvitationUpdate) SetConfirmedAt(v time.Time) *InvitationUpdate {
	_u.mutation.SetConfirmedAt(v)
	return _u
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableConfirmedAt(v *time.Time) *InvitationUpdate {
	if v != nil {
		_u.SetConfirmedAt(*v)
	}
	return _u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (_u *InvitationUpdate) ClearConfirmedAt() *InvitationUpdate {
	_u.mutation.ClearConfirmedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *InvitationUpdate) SetCreatedAt(v time.Time) *InvitationUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableCreatedAt(v *time.Time) *InvitationUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetInviter sets the "inviter" edge to the User entity.
func (_u *InvitationUpdate) SetInviter(v *User) *InvitationUpdate {
	return _u.SetInviterID(v.ID)
}

// SetInvitee sets the "invitee" edge to the User entity.
func (_u *InvitationUpdate) SetInvitee(v *User) *InvitationUpdate {
	return _u.SetInviteeID(v.ID)
}

// SetConfirmedByUserID sets the "confirmed_by_user" edge to the User entity by ID.
func (_u *InvitationUpdate) SetConfirmedByUserID(id int64) *InvitationUpdate {
	_u.mutation.SetConfirmedByUserID(id)
	return _u
}

// SetNillableConfirmedByUserID sets the "confirmed_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *InvitationUpdate) SetNillableConfirmedByUserID(id *int64) *InvitationUpdate {
	if id != nil {
		_u = _u.SetConfirmedByUserID(*id)
	}
	return _u
}

// SetConfirmedByUser sets the "confirmed_by_user" edge to the User entity.
func (_u *InvitationUpdate) SetConfirmedByUser(v *User) *InvitationUpdate {
	return _u.SetConfirmedByUserID(v.ID)
}

// AddLogIDs adds the "logs" edge to the InviteLog entity by IDs.
func (_u *InvitationUpdate) AddLogIDs(ids ...int64) *InvitationUpdate {
	_u.mutation.AddLogIDs(ids...)
	return _u
}

// AddLogs adds the "logs" edges to the InviteLog entity.
func (_u *InvitationUpdate) AddLogs(v ...*InviteLog) *InvitationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLogIDs(ids...)
}

// Mutation returns the InvitationMutation object of the builder.
func (_u *InvitationUpdate) Mutation() *InvitationMutation {
	return _u.mutation
}

// ClearInviter clears the "inviter" edge to the User entity.
func (_u *InvitationUpdate) ClearInviter() *InvitationUpdate {
	_u.mutation.ClearInviter()
	return _u
}

// ClearInvitee clears the "invitee" edge to the User entity.
func (_u *InvitationUpdate) ClearInvitee() *InvitationUpdate {
	_u.mutation.ClearInvitee()
	return _u
}

// ClearConfirmedByUser clears the "confirmed_by_user" edge to the User entity.
func (_u *InvitationUpdate) ClearConfirmedByUser() *InvitationUpdate {
	_u.mutation.ClearConfirmedByUser()
	return _u
}

// ClearLogs clears all "logs" edges to the InviteLog entity.
func (_u *InvitationUpdate) ClearLogs() *InvitationUpdate {
	_u.mutation.ClearLogs()
	return _u
}

// RemoveLogIDs removes the "logs" edge to InviteLog entities by IDs.
func (_u *InvitationUpdate) RemoveLogIDs(ids ...int64) *InvitationUpdate {
	_u.mutation.RemoveLogIDs(ids...)
	return _u
}

// RemoveLogs removes "logs" edges to InviteLog entities.
func (_u *InvitationUpdate) RemoveLogs(v ...*InviteLog) *InvitationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvitationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvitationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvitationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvitationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvitationUpdate) check() error {
	if v, ok := _u.mutation.InviteCode(); ok {
		if err := invitation.InviteCodeValidator(v); err != nil {
			return &ValidationError{Name: "invite_code", err: fmt.Errorf(`ent: validator failed for field "Invitation.invite_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invitation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Invitation.status": %w`, err)}
		}
	}
	if _u.mutation.InviterCleared() && len(_u.mutation.InviterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invitation.inviter"`)
	}
	if _u.mutation.InviteeCleared() && len(_u.mutation.InviteeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invitation.invitee"`)
	}
	return nil
}

func (_u *InvitationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitation.Table, invitation.Columns, sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InviteCode(); ok {
		_spec.SetField(invitation.FieldInviteCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(invitation.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(invitation.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invitation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfirmedAt(); ok {
		_spec.SetField(invitation.FieldConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfirmedAtCleared() {
		_spec.ClearField(invitation.FieldConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(invitation.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.InviterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.InviterTable,
			Columns: []string{invitation.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.InviterTable,
			Columns: []string{invitation.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InviteeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   invitation.InviteeTable,
			Columns: []string{invitation.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   invitation.InviteeTable,
			Columns: []string{invitation.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConfirmedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.ConfirmedByUserTable,
			Columns: []string{invitation.ConfirmedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfirmedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.ConfirmedByUserTable,
			Columns: []string{invitation.ConfirmedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invitation.LogsTable,
			Columns: []string{invitation.LogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLogsIDs(); len(nodes) > 0 && !_u.mutation.LogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invitation.LogsTable,
			Columns: []string{invitation.LogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invitation.LogsTable,
			Columns: []string{invitation.LogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvitationUpdateOne is the builder for updating a single Invitation entity.
type InvitationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvitationMutation
}

// SetInviterID sets the "inviter_id" field.
func (_u *InvitationUpdateOne) SetInviterID(v int64) *InvitationUpdateOne {
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableInviterID(v *int64) *InvitationUpdateOne {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// SetInviteeID sets the "invitee_id" field.
func (_u *InvitationUpdateOne) SetInviteeID(v int64) *InvitationUpdateOne {
	_u.mutation.SetInviteeID(v)
	return _u
}

// SetNillableInviteeID sets the "invitee_id" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableInviteeID(v *int64) *InvitationUpdateOne {
	if v != nil {
		_u.SetInviteeID(*v)
	}
	return _u
}

// SetInviteCode sets the "invite_code" field.
func (_u *InvitationUpdateOne) SetInviteCode(v string) *InvitationUpdateOne {
	_u.mutation.SetInviteCode(v)
	return _u
}

// SetNillableInviteCode sets the "invite_code" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableInviteCode(v *string) *InvitationUpdateOne {
	if v != nil {
		_u.SetInviteCode(*v)
	}
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *InvitationUpdateOne) SetRewardAmount(v float64) *InvitationUpdateOne {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableRewardAmount(v *float64) *InvitationUpdateOne {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *InvitationUpdateOne) AddRewardAmount(v float64) *InvitationUpdateOne {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvitationUpdateOne) SetStatus(v string) *InvitationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableStatus(v *string) *InvitationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConfirmedBy sets the "confirmed_by" field.
func (_u *InvitationUpdateOne) SetConfirmedBy(v int64) *InvitationUpdateOne {
	_u.mutation.SetConfirmedBy(v)
	return _u
}

// SetNillableConfirmedBy sets the "confirmed_by" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableConfirmedBy(v *int64) *InvitationUpdateOne {
	if v != nil {
		_u.SetConfirmedBy(*v)
	}
	return _u
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (_u *InvitationUpdateOne) ClearConfirmedBy() *InvitationUpdateOne {
	_u.mutation.ClearConfirmedBy()
	return _u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_u *InvitationUpdateOne) SetConfirmedAt(v time.Time) *InvitationUpdateOne {
	_u.mutation.SetConfirmedAt(v)
	return _u
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableConfirmedAt(v *time.Time) *InvitationUpdateOne {
	if v != nil {
		_u.SetConfirmedAt(*v)
	}
	return _u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (_u *InvitationUpdateOne) ClearConfirmedAt() *InvitationUpdateOne {
	_u.mutation.ClearConfirmedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *InvitationUpdateOne) SetCreatedAt(v time.Time) *InvitationUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableCreatedAt(v *time.Time) *InvitationUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetInviter sets the "inviter" edge to the User entity.
func (_u *InvitationUpdateOne) SetInviter(v *User) *InvitationUpdateOne {
	return _u.SetInviterID(v.ID)
}

// SetInvitee sets the "invitee" edge to the User entity.
func (_u *InvitationUpdateOne) SetInvitee(v *User) *InvitationUpdateOne {
	return _u.SetInviteeID(v.ID)
}

// SetConfirmedByUserID sets the "confirmed_by_user" edge to the User entity by ID.
func (_u *InvitationUpdateOne) SetConfirmedByUserID(id int64) *InvitationUpdateOne {
	_u.mutation.SetConfirmedByUserID(id)
	return _u
}

// SetNillableConfirmedByUserID sets the "confirmed_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableConfirmedByUserID(id *int64) *InvitationUpdateOne {
	if id != nil {
		_u = _u.SetConfirmedByUserID(*id)
	}
	return _u
}

// SetConfirmedByUser sets the "confirmed_by_user" edge to the User entity.
func (_u *InvitationUpdateOne) SetConfirmedByUser(v *User) *InvitationUpdateOne {
	return _u.SetConfirmedByUserID(v.ID)
}

// AddLogIDs adds the "logs" edge to the InviteLog entity by IDs.
func (_u *InvitationUpdateOne) AddLogIDs(ids ...int64) *InvitationUpdateOne {
	_u.mutation.AddLogIDs(ids...)
	return _u
}

// AddLogs adds the "logs" edges to the InviteLog entity.
func (_u *InvitationUpdateOne) AddLogs(v ...*InviteLog) *InvitationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLogIDs(ids...)
}

// Mutation returns the InvitationMutation object of the builder.
func (_u *InvitationUpdateOne) Mutation() *InvitationMutation {
	return _u.mutation
}

// ClearInviter clears the "inviter" edge to the User entity.
func (_u *InvitationUpdateOne) ClearInviter() *InvitationUpdateOne {
	_u.mutation.ClearInviter()
	return _u
}

// ClearInvitee clears the "invitee" edge to the User entity.
func (_u *InvitationUpdateOne) ClearInvitee() *InvitationUpdateOne {
	_u.mutation.ClearInvitee()
	return _u
}

// ClearConfirmedByUser clears the "confirmed_by_user" edge to the User entity.
func (_u *InvitationUpdateOne) ClearConfirmedByUser() *InvitationUpdateOne {
	_u.mutation.ClearConfirmedByUser()
	return _u
}

// ClearLogs clears all "logs" edges to the InviteLog entity.
func (_u *InvitationUpdateOne) ClearLogs() *InvitationUpdateOne {
	_u.mutation.ClearLogs()
	return _u
}

// RemoveLogIDs removes the "logs" edge to InviteLog entities by IDs.
func (_u *InvitationUpdateOne) RemoveLogIDs(ids ...int64) *InvitationUpdateOne {
	_u.mutation.RemoveLogIDs(ids...)
	return _u
}

// RemoveLogs removes "logs" edges to InviteLog entities.
func (_u *InvitationUpdateOne) RemoveLogs(v ...*InviteLog) *InvitationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLogIDs(ids...)
}

// Where appends a list predicates to the InvitationUpdate builder.
func (_u *InvitationUpdateOne) Where(ps ...predicate.Invitation) *InvitationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvitationUpdateOne) Select(field string, fields ...string) *InvitationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Invitation entity.
func (_u *InvitationUpdateOne) Save(ctx context.Context) (*Invitation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvitationUpdateOne) SaveX(ctx context.Context) *Invitation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvitationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvitationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvitationUpdateOne) check() error {
	if v, ok := _u.mutation.InviteCode(); ok {
		if err := invitation.InviteCodeValidator(v); err != nil {
			return &ValidationError{Name: "invite_code", err: fmt.Errorf(`ent: validator failed for field "Invitation.invite_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invitation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Invitation.status": %w`, err)}
		}
	}
	if _u.mutation.InviterCleared() && len(_u.mutation.InviterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invitation.inviter"`)
	}
	if _u.mutation.InviteeCleared() && len(_u.mutation.InviteeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invitation.invitee"`)
	}
	return nil
}

func (_u *InvitationUpdateOne) sqlSave(ctx context.Context) (_node *Invitation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitation.Table, invitation.Columns, sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Invitation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invitation.FieldID)
		for _, f := range fields {
			if !invitation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invitation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InviteCode(); ok {
		_spec.SetField(invitation.FieldInviteCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(invitation.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(invitation.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invitation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfirmedAt(); ok {
		_spec.SetField(invitation.FieldConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfirmedAtCleared() {
		_spec.ClearField(invitation.FieldConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(invitation.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.InviterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.InviterTable,
			Columns: []string{invitation.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.InviterTable,
			Columns: []string{invitation.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InviteeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   invitation.InviteeTable,
			Columns: []string{invitation.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   invitation.InviteeTable,
			Columns: []string{invitation.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConfirmedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.ConfirmedByUserTable,
			Columns: []string{invitation.ConfirmedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfirmedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.ConfirmedByUserTable,
			Columns: []string{invitation.ConfirmedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invitation.LogsTable,
			Columns: []string{invitation.LogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLogsIDs(); len(nodes) > 0 && !_u.mutation.LogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invitation.LogsTable,
			Columns: []string{invitation.LogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invitation.LogsTable,
			Columns: []string{invitation.LogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Invitation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
