// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invitation"
	"github.com/Wei-Shaw/sub2api/ent/invitelog"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InviteLogUpdate is the builder for updating InviteLog entities.
type InviteLogUpdate struct {
	config
	hooks    []Hook
	mutation *InviteLogMutation
}

// Where appends a list predicates to the InviteLogUpdate builder.
func (_u *InviteLogUpdate) Where(ps ...predicate.InviteLog) *InviteLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInviteID sets the "invite_id" field.
func (_u *InviteLogUpdate) SetInviteID(v int64) *InviteLogUpdate {
	_u.mutation.SetInviteID(v)
	return _u
}

// SetNillableInviteID sets the "invite_id" field if the given value is not nil.
func (_u *InviteLogUpdate) SetNillableInviteID(v *int64) *InviteLogUpdate {
	if v != nil {
		_u.SetInviteID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *InviteLogUpdate) SetAction(v string) *InviteLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *InviteLogUpdate) SetNillableAction(v *string) *InviteLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetInviterID sets the "inviter_id" field.
func (_u *InviteLogUpdate) SetInviterID(v int64) *InviteLogUpdate {
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *InviteLogUpdate) SetNillableInviterID(v *int64) *InviteLogUpdate {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// SetInviteeID sets the "invitee_id" field.
func (_u *InviteLogUpdate) SetInviteeID(v int64) *InviteLogUpdate {
	_u.mutation.SetInviteeID(v)
	return _u
}

// SetNillableInviteeID sets the "invitee_id" field if the given value is not nil.
func (_u *InviteLogUpdate) SetNillableInviteeID(v *int64) *InviteLogUpdate {
	if v != nil {
		_u.SetInviteeID(*v)
	}
	return _u
}

// SetAdminID sets the "admin_id" field.
func (_u *InviteLogUpdate) SetAdminID(v int64) *InviteLogUpdate {
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *InviteLogUpdate) SetNillableAdminID(v *int64) *InviteLogUpdate {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// ClearAdminID clears the value of the "admin_id" field.
func (_u *InviteLogUpdate) ClearAdminID() *InviteLogUpdate {
	_u.mutation.ClearAdminID()
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *InviteLogUpdate) SetRewardAmount(v float64) *InviteLogUpdate {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *InviteLogUpdate) SetNillableRewardAmount(v *float64) *InviteLogUpdate {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *InviteLogUpdate) AddRewardAmount(v float64) *InviteLogUpdate {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *InviteLogUpdate) SetCreatedAt(v time.Time) *InviteLogUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *InviteLogUpdate) SetNillableCreatedAt(v *time.Time) *InviteLogUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetInvite sets the "invite" edge to the Invitation entity.
func (_u *InviteLogUpdate) SetInvite(v *Invitation) *InviteLogUpdate {
	return _u.SetInviteID(v.ID)
}

// SetInviter sets the "inviter" edge to the User entity.
func (_u *InviteLogUpdate) SetInviter(v *User) *InviteLogUpdate {
	return _u.SetInviterID(v.ID)
}

// SetInvitee sets the "invitee" edge to the User entity.
func (_u *InviteLogUpdate) SetInvitee(v *User) *InviteLogUpdate {
	return _u.SetInviteeID(v.ID)
}

// SetAdmin sets the "admin" edge to the User entity.
func (_u *InviteLogUpdate) SetAdmin(v *User) *InviteLogUpdate {
	return _u.SetAdminID(v.ID)
}

// Mutation returns the InviteLogMutation object of the builder.
func (_u *InviteLogUpdate) Mutation() *InviteLogMutation {
	return _u.mutation
}

// ClearInvite clears the "invite" edge to the Invitation entity.
func (_u *InviteLogUpdate) ClearInvite() *InviteLogUpdate {
	_u.mutation.ClearInvite()
	return _u
}

// ClearInviter clears the "inviter" edge to the User entity.
func (_u *InviteLogUpdate) ClearInviter() *InviteLogUpdate {
	_u.mutation.ClearInviter()
	return _u
}

// ClearInvitee clears the "invitee" edge to the User entity.
func (_u *InviteLogUpdate) ClearInvitee() *InviteLogUpdate {
	_u.mutation.ClearInvitee()
	return _u
}

// ClearAdmin clears the "admin" edge to the User entity.
func (_u *InviteLogUpdate) ClearAdmin() *InviteLogUpdate {
	_u.mutation.ClearAdmin()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InviteLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InviteLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InviteLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InviteLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InviteLogUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := invitelog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "InviteLog.action": %w`, err)}
		}
	}
	if _u.mutation.InviteCleared() && len(_u.mutation.InviteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InviteLog.invite"`)
	}
	if _u.mutation.InviterCleared() && len(_u.mutation.InviterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InviteLog.inviter"`)
	}
	if _u.mutation.InviteeCleared() && len(_u.mutation.InviteeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InviteLog.invitee"`)
	}
	return nil
}

func (_u *InviteLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitelog.Table, invitelog.Columns, sqlgraph.NewFieldSpec(invitelog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(invitelog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(invitelog.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(invitelog.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(invitelog.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.InviteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.InviteTable,
			Columns: []string{invitelog.InviteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.InviteTable,
			Columns: []string{invitelog.InviteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InviterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.InviterTable,
			Columns: []string{invitelog.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.InviterTable,
			Columns: []string{invitelog.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InviteeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.InviteeTable,
			Columns: []string{invitelog.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.InviteeTable,
			Columns: []string{invitelog.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.AdminTable,
			Columns: []string{invitelog.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.AdminTable,
			Columns: []string{invitelog.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InviteLogUpdateOne is the builder for updating a single InviteLog entity.
type InviteLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InviteLogMutation
}

// SetInviteID sets the "invite_id" field.
func (_u *InviteLogUpdateOne) SetInviteID(v int64) *InviteLogUpdateOne {
	_u.mutation.SetInviteID(v)
	return _u
}

// SetNillableInviteID sets the "invite_id" field if the given value is not nil.
func (_u *InviteLogUpdateOne) SetNillableInviteID(v *int64) *InviteLogUpdateOne {
	if v != nil {
		_u.SetInviteID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *InviteLogUpdateOne) SetAction(v string) *InviteLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *InviteLogUpdateOne) SetNillableAction(v *string) *InviteLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetInviterID sets the "inviter_id" field.
func (_u *InviteLogUpdateOne) SetInviterID(v int64) *InviteLogUpdateOne {
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *InviteLogUpdateOne) SetNillableInviterID(v *int64) *InviteLogUpdateOne {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// SetInviteeID sets the "invitee_id" field.
func (_u *InviteLogUpdateOne) SetInviteeID(v int64) *InviteLogUpdateOne {
	_u.mutation.SetInviteeID(v)
	return _u
}

// SetNillableInviteeID sets the "invitee_id" field if the given value is not nil.
func (_u *InviteLogUpdateOne) SetNillableInviteeID(v *int64) *InviteLogUpdateOne {
	if v != nil {
		_u.SetInviteeID(*v)
	}
	return _u
}

// SetAdminID sets the "admin_id" field.
func (_u *InviteLogUpdateOne) SetAdminID(v int64) *InviteLogUpdateOne {
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *InviteLogUpdateOne) SetNillableAdminID(v *int64) *InviteLogUpdateOne {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// ClearAdminID clears the value of the "admin_id" field.
func (_u *InviteLogUpdateOne) ClearAdminID() *InviteLogUpdateOne {
	_u.mutation.ClearAdminID()
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *InviteLogUpdateOne) SetRewardAmount(v float64) *InviteLogUpdateOne {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *InviteLogUpdateOne) SetNillableRewardAmount(v *float64) *InviteLogUpdateOne {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *InviteLogUpdateOne) AddRewardAmount(v float64) *InviteLogUpdateOne {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *InviteLogUpdateOne) SetCreatedAt(v time.Time) *InviteLogUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *InviteLogUpdateOne) SetNillableCreatedAt(v *time.Time) *InviteLogUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetInvite sets the "invite" edge to the Invitation entity.
func (_u *InviteLogUpdateOne) SetInvite(v *Invitation) *InviteLogUpdateOne {
	return _u.SetInviteID(v.ID)
}

// SetInviter sets the "inviter" edge to the User entity.
func (_u *InviteLogUpdateOne) SetInviter(v *User) *InviteLogUpdateOne {
	return _u.SetInviterID(v.ID)
}

// SetInvitee sets the "invitee" edge to the User entity.
func (_u *InviteLogUpdateOne) SetInvitee(v *User) *InviteLogUpdateOne {
	return _u.SetInviteeID(v.ID)
}

// SetAdmin sets the "admin" edge to the User entity.
func (_u *InviteLogUpdateOne) SetAdmin(v *User) *InviteLogUpdateOne {
	return _u.SetAdminID(v.ID)
}

// Mutation returns the InviteLogMutation object of the builder.
func (_u *InviteLogUpdateOne) Mutation() *InviteLogMutation {
	return _u.mutation
}

// ClearInvite clears the "invite" edge to the Invitation entity.
func (_u *InviteLogUpdateOne) ClearInvite() *InviteLogUpdateOne {
	_u.mutation.ClearInvite()
	return _u
}

// ClearInviter clears the "inviter" edge to the User entity.
func (_u *InviteLogUpdateOne) ClearInviter() *InviteLogUpdateOne {
	_u.mutation.ClearInviter()
	return _u
}

// ClearInvitee clears the "invitee" edge to the User entity.
func (_u *InviteLogUpdateOne) ClearInvitee() *InviteLogUpdateOne {
	_u.mutation.ClearInvitee()
	return _u
}

// ClearAdmin clears the "admin" edge to the User entity.
func (_u *InviteLogUpdateOne) ClearAdmin() *InviteLogUpdateOne {
	_u.mutation.ClearAdmin()
	return _u
}

// Where appends a list predicates to the InviteLogUpdate builder.
func (_u *InviteLogUpdateOne) Where(ps ...predicate.InviteLog) *InviteLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InviteLogUpdateOne) Select(field string, fields ...string) *InviteLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InviteLog entity.
func (_u *InviteLogUpdateOne) Save(ctx context.Context) (*InviteLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InviteLogUpdateOne) SaveX(ctx context.Context) *InviteLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InviteLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InviteLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InviteLogUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := invitelog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "InviteLog.action": %w`, err)}
		}
	}
	if _u.mutation.InviteCleared() && len(_u.mutation.InviteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InviteLog.invite"`)
	}
	if _u.mutation.InviterCleared() && len(_u.mutation.InviterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InviteLog.inviter"`)
	}
	if _u.mutation.InviteeCleared() && len(_u.mutation.InviteeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InviteLog.invitee"`)
	}
	return nil
}

func (_u *InviteLogUpdateOne) sqlSave(ctx context.Context) (_node *InviteLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitelog.Table, invitelog.Columns, sqlgraph.NewFieldSpec(invitelog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InviteLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invitelog.FieldID)
		for _, f := range fields {
			if !invitelog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invitelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(invitelog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(invitelog.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(invitelog.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(invitelog.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.InviteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.InviteTable,
			Columns: []string{invitelog.InviteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.InviteTable,
			Columns: []string{invitelog.InviteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InviterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.InviterTable,
			Columns: []string{invitelog.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.InviterTable,
			Columns: []string{invitelog.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InviteeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.InviteeTable,
			Columns: []string{invitelog.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.InviteeTable,
			Columns: []string{invitelog.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.AdminTable,
			Columns: []string{invitelog.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.AdminTable,
			Columns: []string{invitelog.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InviteLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
