// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invitation"
	"github.com/Wei-Shaw/sub2api/ent/invitelog"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InviteLogQuery is the builder for querying InviteLog entities.
type InviteLogQuery struct {
	config
	ctx         *QueryContext
	order       []invitelog.OrderOption
	inters      []Interceptor
	predicates  []predicate.InviteLog
	withInvite  *InvitationQuery
	withInviter *UserQuery
	withInvitee *UserQuery
	withAdmin   *UserQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the InviteLogQuery builder.
func (_q *InviteLogQuery) Where(ps ...predicate.InviteLog) *InviteLogQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *InviteLogQuery) Limit(limit int) *InviteLogQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *InviteLogQuery) Offset(offset int) *InviteLogQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *InviteLogQuery) Unique(unique bool) *InviteLogQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *InviteLogQuery) Order(o ...invitelog.OrderOption) *InviteLogQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryInvite chains the current query on the "invite" edge.
func (_q *InviteLogQuery) QueryInvite() *InvitationQuery {
	query := (&InvitationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(invitelog.Table, invitelog.FieldID, selector),
			sqlgraph.To(invitation.Table, invitation.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, invitelog.InviteTable, invitelog.InviteColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryInviter chains the current query on the "inviter" edge.
func (_q *InviteLogQuery) QueryInviter() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(invitelog.Table, invitelog.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, invitelog.InviterTable, invitelog.InviterColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryInvitee chains the current query on the "invitee" edge.
func (_q *InviteLogQuery) QueryInvitee() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(invitelog.Table, invitelog.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, invitelog.InviteeTable, invitelog.InviteeColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAdmin chains the current query on the "admin" edge.
func (_q *InviteLogQuery) QueryAdmin() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(invitelog.Table, invitelog.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, invitelog.AdminTable, invitelog.AdminColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first InviteLog entity from the query.
// Returns a *NotFoundError when no InviteLog was found.
func (_q *InviteLogQuery) First(ctx context.Context) (*InviteLog, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{invitelog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *InviteLogQuery) FirstX(ctx context.Context) *InviteLog {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first InviteLog ID from the query.
// Returns a *NotFoundError when no InviteLog ID was found.
func (_q *InviteLogQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{invitelog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *InviteLogQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single InviteLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one InviteLog entity is found.
// Returns a *NotFoundError when no InviteLog entities are found.
func (_q *InviteLogQuery) Only(ctx context.Context) (*InviteLog, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{invitelog.Label}
	default:
		return nil, &NotSingularError{invitelog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *InviteLogQuery) OnlyX(ctx context.Context) *InviteLog {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only InviteLog ID in the query.
// Returns a *NotSingularError when more than one InviteLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *InviteLogQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{invitelog.Label}
	default:
		err = &NotSingularError{invitelog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *InviteLogQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of InviteLogs.
func (_q *InviteLogQuery) All(ctx context.Context) ([]*InviteLog, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*InviteLog, *InviteLogQuery]()
	return withInterceptors[[]*InviteLog](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *InviteLogQuery) AllX(ctx context.Context) []*InviteLog {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of InviteLog IDs.
func (_q *InviteLogQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(invitelog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *InviteLogQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *InviteLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*InviteLogQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *InviteLogQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *InviteLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *InviteLogQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the InviteLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *InviteLogQuery) Clone() *InviteLogQuery {
	if _q == nil {
		return nil
	}
	return &InviteLogQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]invitelog.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.InviteLog{}, _q.predicates...),
		withInvite:  _q.withInvite.Clone(),
		withInviter: _q.withInviter.Clone(),
		withInvitee: _q.withInvitee.Clone(),
		withAdmin:   _q.withAdmin.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithInvite tells the query-builder to eager-load the nodes that are connected to
// the "invite" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *InviteLogQuery) WithInvite(opts ...func(*InvitationQuery)) *InviteLogQuery {
	query := (&InvitationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withInvite = query
	return _q
}

// WithInviter tells the query-builder to eager-load the nodes that are connected to
// the "inviter" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *InviteLogQuery) WithInviter(opts ...func(*UserQuery)) *InviteLogQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withInviter = query
	return _q
}

// WithInvitee tells the query-builder to eager-load the nodes that are connected to
// the "invitee" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *InviteLogQuery) WithInvitee(opts ...func(*UserQuery)) *InviteLogQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withInvitee = query
	return _q
}

// WithAdmin tells the query-builder to eager-load the nodes that are connected to
// the "admin" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *InviteLogQuery) WithAdmin(opts ...func(*UserQuery)) *InviteLogQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAdmin = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		InviteID int64 `json:"invite_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.InviteLog.Query().
//		GroupBy(invitelog.FieldInviteID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *InviteLogQuery) GroupBy(field string, fields ...string) *InviteLogGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &InviteLogGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = invitelog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		InviteID int64 `json:"invite_id,omitempty"`
//	}
//
//	client.InviteLog.Query().
//		Select(invitelog.FieldInviteID).
//		Scan(ctx, &v)
func (_q *InviteLogQuery) Select(fields ...string) *InviteLogSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &InviteLogSelect{InviteLogQuery: _q}
	sbuild.label = invitelog.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a InviteLogSelect configured with the given aggregations.
func (_q *InviteLogQuery) Aggregate(fns ...AggregateFunc) *InviteLogSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *InviteLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !invitelog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *InviteLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*InviteLog, error) {
	var (
		nodes       = []*InviteLog{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withInvite != nil,
			_q.withInviter != nil,
			_q.withInvitee != nil,
			_q.withAdmin != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*InviteLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &InviteLog{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withInvite; query != nil {
		if err := _q.loadInvite(ctx, query, nodes, nil,
			func(n *InviteLog, e *Invitation) { n.Edges.Invite = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withInviter; query != nil {
		if err := _q.loadInviter(ctx, query, nodes, nil,
			func(n *InviteLog, e *User) { n.Edges.Inviter = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withInvitee; query != nil {
		if err := _q.loadInvitee(ctx, query, nodes, nil,
			func(n *InviteLog, e *User) { n.Edges.Invitee = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAdmin; query != nil {
		if err := _q.loadAdmin(ctx, query, nodes, nil,
			func(n *InviteLog, e *User) { n.Edges.Admin = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *InviteLogQuery) loadInvite(ctx context.Context, query *InvitationQuery, nodes []*InviteLog, init func(*InviteLog), assign func(*InviteLog, *Invitation)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*InviteLog)
	for i := range nodes {
		fk := nodes[i].InviteID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(invitation.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "invite_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *InviteLogQuery) loadInviter(ctx context.Context, query *UserQuery, nodes []*InviteLog, init func(*InviteLog), assign func(*InviteLog, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*InviteLog)
	for i := range nodes {
		fk := nodes[i].InviterID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "inviter_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *InviteLogQuery) loadInvitee(ctx context.Context, query *UserQuery, nodes []*InviteLog, init func(*InviteLog), assign func(*InviteLog, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*InviteLog)
	for i := range nodes {
		fk := nodes[i].InviteeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "invitee_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *InviteLogQuery) loadAdmin(ctx context.Context, query *UserQuery, nodes []*InviteLog, init func(*InviteLog), assign func(*InviteLog, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*InviteLog)
	for i := range nodes {
		if nodes[i].AdminID == nil {
			continue
		}
		fk := *nodes[i].AdminID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "admin_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *InviteLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *InviteLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(invitelog.Table, invitelog.Columns, sqlgraph.NewFieldSpec(invitelog.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invitelog.FieldID)
		for i := range fields {
			if fields[i] != invitelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withInvite != nil {
			_spec.Node.AddColumnOnce(invitelog.FieldInviteID)
		}
		if _q.withInviter != nil {
			_spec.Node.AddColumnOnce(invitelog.FieldInviterID)
		}
		if _q.withInvitee != nil {
			_spec.Node.AddColumnOnce(invitelog.FieldInviteeID)
		}
		if _q.withAdmin != nil {
			_spec.Node.AddColumnOnce(invitelog.FieldAdminID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *InviteLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(invitelog.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = invitelog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *InviteLogQuery) ForUpdate(opts ...sql.LockOption) *InviteLogQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *InviteLogQuery) ForShare(opts ...sql.LockOption) *InviteLogQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// InviteLogGroupBy is the group-by builder for InviteLog entities.
type InviteLogGroupBy struct {
	selector
	build *InviteLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *InviteLogGroupBy) Aggregate(fns ...AggregateFunc) *InviteLogGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *InviteLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InviteLogQuery, *InviteLogGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *InviteLogGroupBy) sqlScan(ctx context.Context, root *InviteLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// InviteLogSelect is the builder for selecting fields of InviteLog entities.
type InviteLogSelect struct {
	*InviteLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *InviteLogSelect) Aggregate(fns ...AggregateFunc) *InviteLogSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *InviteLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InviteLogQuery, *InviteLogSelect](ctx, _s.InviteLogQuery, _s, _s.inters, v)
}

func (_s *InviteLogSelect) sqlScan(ctx context.Context, root *InviteLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
