// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/invitation"
	"github.com/Wei-Shaw/sub2api/ent/invitelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InviteLog is the model entity for the InviteLog schema.
type InviteLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// InviteID holds the value of the "invite_id" field.
	InviteID int64 `json:"invite_id,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// InviterID holds the value of the "inviter_id" field.
	InviterID int64 `json:"inviter_id,omitempty"`
	// InviteeID holds the value of the "invitee_id" field.
	InviteeID int64 `json:"invitee_id,omitempty"`
	// AdminID holds the value of the "admin_id" field.
	AdminID *int64 `json:"admin_id,omitempty"`
	// RewardAmount holds the value of the "reward_amount" field.
	RewardAmount float64 `json:"reward_amount,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InviteLogQuery when eager-loading is set.
	Edges        InviteLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InviteLogEdges holds the relations/edges for other nodes in the graph.
type InviteLogEdges struct {
	// Invite holds the value of the invite edge.
	Invite *Invitation `json:"invite,omitempty"`
	// Inviter holds the value of the inviter edge.
	Inviter *User `json:"inviter,omitempty"`
	// Invitee holds the value of the invitee edge.
	Invitee *User `json:"invitee,omitempty"`
	// Admin holds the value of the admin edge.
	Admin *User `json:"admin,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// InviteOrErr returns the Invite value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InviteLogEdges) InviteOrErr() (*Invitation, error) {
	if e.Invite != nil {
		return e.Invite, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: invitation.Label}
	}
	return nil, &NotLoadedError{edge: "invite"}
}

// InviterOrErr returns the Inviter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InviteLogEdges) InviterOrErr() (*User, error) {
	if e.Inviter != nil {
		return e.Inviter, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "inviter"}
}

// InviteeOrErr returns the Invitee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InviteLogEdges) InviteeOrErr() (*User, error) {
	if e.Invitee != nil {
		return e.Invitee, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "invitee"}
}

// AdminOrErr returns the Admin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InviteLogEdges) AdminOrErr() (*User, error) {
	if e.Admin != nil {
		return e.Admin, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "admin"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InviteLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invitelog.FieldRewardAmount:
			values[i] = new(sql.NullFloat64)
		case invitelog.FieldID, invitelog.FieldInviteID, invitelog.FieldInviterID, invitelog.FieldInviteeID, invitelog.FieldAdminID:
			values[i] = new(sql.NullInt64)
		case invitelog.FieldAction:
			values[i] = new(sql.NullString)
		case invitelog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InviteLog fields.
func (_m *InviteLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invitelog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invitelog.FieldInviteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invite_id", values[i])
			} else if value.Valid {
				_m.InviteID = value.Int64
			}
		case invitelog.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case invitelog.FieldInviterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field inviter_id", values[i])
			} else if value.Valid {
				_m.InviterID = value.Int64
			}
		case invitelog.FieldInviteeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_id", values[i])
			} else if value.Valid {
				_m.InviteeID = value.Int64
			}
		case invitelog.FieldAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field admin_id", values[i])
			} else if value.Valid {
				_m.AdminID = new(int64)
				*_m.AdminID = value.Int64
			}
		case invitelog.FieldRewardAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_amount", values[i])
			} else if value.Valid {
				_m.RewardAmount = value.Float64
			}
		case invitelog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InviteLog.
// This includes values selected through modifiers, order, etc.
func (_m *InviteLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInvite queries the "invite" edge of the InviteLog entity.
func (_m *InviteLog) QueryInvite() *InvitationQuery {
	return NewInviteLogClient(_m.config).QueryInvite(_m)
}

// QueryInviter queries the "inviter" edge of the InviteLog entity.
func (_m *InviteLog) QueryInviter() *UserQuery {
	return NewInviteLogClient(_m.config).QueryInviter(_m)
}

// QueryInvitee queries the "invitee" edge of the InviteLog entity.
func (_m *InviteLog) QueryInvitee() *UserQuery {
	return NewInviteLogClient(_m.config).QueryInvitee(_m)
}

// QueryAdmin queries the "admin" edge of the InviteLog entity.
func (_m *InviteLog) QueryAdmin() *UserQuery {
	return NewInviteLogClient(_m.config).QueryAdmin(_m)
}

// Update returns a builder for updating this InviteLog.
// Note that you need to call InviteLog.Unwrap() before calling this method if this InviteLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InviteLog) Update() *InviteLogUpdateOne {
	return NewInviteLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InviteLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InviteLog) Unwrap() *InviteLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InviteLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InviteLog) String() string {
	var builder strings.Builder
	builder.WriteString("InviteLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("invite_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviteID))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("inviter_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviterID))
	builder.WriteString(", ")
	builder.WriteString("invitee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviteeID))
	builder.WriteString(", ")
	if v := _m.AdminID; v != nil {
		builder.WriteString("admin_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("reward_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardAmount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InviteLogs is a parsable slice of InviteLog.
type InviteLogs []*InviteLog
