// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invitation"
	"github.com/Wei-Shaw/sub2api/ent/invitelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvitationCreate is the builder for creating a Invitation entity.
type InvitationCreate struct {
	config
	mutation *InvitationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInviterID sets the "inviter_id" field.
func (_c *InvitationCreate) SetInviterID(v int64) *InvitationCreate {
	_c.mutation.SetInviterID(v)
	return _c
}

// SetInviteeID sets the "invitee_id" field.
func (_c *InvitationCreate) SetInviteeID(v int64) *InvitationCreate {
	_c.mutation.SetInviteeID(v)
	return _c
}

// SetInviteCode sets the "invite_code" field.
func (_c *InvitationCreate) SetInviteCode(v string) *InvitationCreate {
	_c.mutation.SetInviteCode(v)
	return _c
}

// SetRewardAmount sets the "reward_amount" field.
func (_c *InvitationCreate) SetRewardAmount(v float64) *InvitationCreate {
	_c.mutation.SetRewardAmount(v)
	return _c
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_c *InvitationCreate) SetNillableRewardAmount(v *float64) *InvitationCreate {
	if v != nil {
		_c.SetRewardAmount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvitationCreate) SetStatus(v string) *InvitationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InvitationCreate) SetNillableStatus(v *string) *InvitationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetConfirmedBy sets the "confirmed_by" field.
func (_c *InvitationCreate) SetConfirmedBy(v int64) *InvitationCreate {
	_c.mutation.SetConfirmedBy(v)
	return _c
}

// SetNillableConfirmedBy sets the "confirmed_by" field if the given value is not nil.
func (_c *InvitationCreate) SetNillableConfirmedBy(v *int64) *InvitationCreate {
	if v != nil {
		_c.SetConfirmedBy(*v)
	}
	return _c
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_c *InvitationCreate) SetConfirmedAt(v time.Time) *InvitationCreate {
	_c.mutation.SetConfirmedAt(v)
	return _c
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_c *InvitationCreate) SetNillableConfirmedAt(v *time.Time) *InvitationCreate {
	if v != nil {
		_c.SetConfirmedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvitationCreate) SetCreatedAt(v time.Time) *InvitationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvitationCreate) SetNillableCreatedAt(v *time.Time) *InvitationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetInviter sets the "inviter" edge to the User entity.
func (_c *InvitationCreate) SetInviter(v *User) *InvitationCreate {
	return _c.SetInviterID(v.ID)
}

// SetInvitee sets the "invitee" edge to the User entity.
func (_c *InvitationCreate) SetInvitee(v *User) *InvitationCreate {
	return _c.SetInviteeID(v.ID)
}

// SetConfirmedByUserID sets the "confirmed_by_user" edge to the User entity by ID.
func (_c *InvitationCreate) SetConfirmedByUserID(id int64) *InvitationCreate {
	_c.mutation.SetConfirmedByUserID(id)
	return _c
}

// SetNillableConfirmedByUserID sets the "confirmed_by_user" edge to the User entity by ID if the given value is not nil.
func (_c *InvitationCreate) SetNillableConfirmedByUserID(id *int64) *InvitationCreate {
	if id != nil {
		_c = _c.SetConfirmedByUserID(*id)
	}
	return _c
}

// SetConfirmedByUser sets the "confirmed_by_user" edge to the User entity.
func (_c *InvitationCreate) SetConfirmedByUser(v *User) *InvitationCreate {
	return _c.SetConfirmedByUserID(v.ID)
}

// AddLogIDs adds the "logs" edge to the InviteLog entity by IDs.
func (_c *InvitationCreate) AddLogIDs(ids ...int64) *InvitationCreate {
	_c.mutation.AddLogIDs(ids...)
	return _c
}

// AddLogs adds the "logs" edges to the InviteLog entity.
func (_c *InvitationCreate) AddLogs(v ...*InviteLog) *InvitationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLogIDs(ids...)
}

// Mutation returns the InvitationMutation object of the builder.
func (_c *InvitationCreate) Mutation() *InvitationMutation {
	return _c.mutation
}

// Save creates the Invitation in the database.
func (_c *InvitationCreate) Save(ctx context.Context) (*Invitation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvitationCreate) SaveX(ctx context.Context) *Invitation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvitationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvitationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvitationCreate) defaults() {
	if _, ok := _c.mutation.RewardAmount(); !ok {
		v := invitation.DefaultRewardAmount
		_c.mutation.SetRewardAmount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := invitation.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invitation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvitationCreate) check() error {
	if _, ok := _c.mutation.InviterID(); !ok {
		return &ValidationError{Name: "inviter_id", err: errors.New(`ent: missing required field "Invitation.inviter_id"`)}
	}
	if _, ok := _c.mutation.InviteeID(); !ok {
		return &ValidationError{Name: "invitee_id", err: errors.New(`ent: missing required field "Invitation.invitee_id"`)}
	}
	if _, ok := _c.mutation.InviteCode(); !ok {
		return &ValidationError{Name: "invite_code", err: errors.New(`ent: missing required field "Invitation.invite_code"`)}
	}
	if v, ok := _c.mutation.InviteCode(); ok {
		if err := invitation.InviteCodeValidator(v); err != nil {
			return &ValidationError{Name: "invite_code", err: fmt.Errorf(`ent: validator failed for field "Invitation.invite_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RewardAmount(); !ok {
		return &ValidationError{Name: "reward_amount", err: errors.New(`ent: missing required field "Invitation.reward_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Invitation.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invitation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Invitation.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Invitation.created_at"`)}
	}
	if len(_c.mutation.InviterIDs()) == 0 {
		return &ValidationError{Name: "inviter", err: errors.New(`ent: missing required edge "Invitation.inviter"`)}
	}
	if len(_c.mutation.InviteeIDs()) == 0 {
		return &ValidationError{Name: "invitee", err: errors.New(`ent: missing required edge "Invitation.invitee"`)}
	}
	return nil
}

func (_c *InvitationCreate) sqlSave(ctx context.Context) (*Invitation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvitationCreate) createSpec() (*Invitation, *sqlgraph.CreateSpec) {
	var (
		_node = &Invitation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invitation.Table, sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.InviteCode(); ok {
		_spec.SetField(invitation.FieldInviteCode, field.TypeString, value)
		_node.InviteCode = value
	}
	if value, ok := _c.mutation.RewardAmount(); ok {
		_spec.SetField(invitation.FieldRewardAmount, field.TypeFloat64, value)
		_node.RewardAmount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invitation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ConfirmedAt(); ok {
		_spec.SetField(invitation.FieldConfirmedAt, field.TypeTime, value)
		_node.ConfirmedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invitation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.InviterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.InviterTable,
			Columns: []string{invitation.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InviterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InviteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   invitation.InviteeTable,
			Columns: []string{invitation.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InviteeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ConfirmedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.ConfirmedByUserTable,
			Columns: []string{invitation.ConfirmedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConfirmedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invitation.LogsTable,
			Columns: []string{invitation.LogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invitation.Create().
//		SetInviterID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvitationUpsert) {
//			SetInviterID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvitationCreate) OnConflict(opts ...sql.ConflictOption) *InvitationUpsertOne {
	_c.conflict = opts
	return &InvitationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invitation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvitationCreate) OnConflictColumns(columns ...string) *InvitationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvitationUpsertOne{
		create: _c,
	}
}

type (
	// InvitationUpsertOne is the builder for "upsert"-ing
	//  one Invitation node.
	InvitationUpsertOne struct {
		create *InvitationCreate
	}

	// InvitationUpsert is the "OnConflict" setter.
	InvitationUpsert struct {
		*sql.UpdateSet
	}
)

// SetInviterID sets the "inviter_id" field.
func (u *InvitationUpsert) SetInviterID(v int64) *InvitationUpsert {
	u.Set(invitation.FieldInviterID, v)
	return u
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateInviterID() *InvitationUpsert {
	u.SetExcluded(invitation.FieldInviterID)
	return u
}

// SetInviteeID sets the "invitee_id" field.
func (u *InvitationUpsert) SetInviteeID(v int64) *InvitationUpsert {
	u.Set(invitation.FieldInviteeID, v)
	return u
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateInviteeID() *InvitationUpsert {
	u.SetExcluded(invitation.FieldInviteeID)
	return u
}

// SetInviteCode sets the "invite_code" field.
func (u *InvitationUpsert) SetInviteCode(v string) *InvitationUpsert {
	u.Set(invitation.FieldInviteCode, v)
	return u
}

// UpdateInviteCode sets the "invite_code" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateInviteCode() *InvitationUpsert {
	u.SetExcluded(invitation.FieldInviteCode)
	return u
}

// SetRewardAmount sets the "reward_amount" field.
func (u *InvitationUpsert) SetRewardAmount(v float64) *InvitationUpsert {
	u.Set(invitation.FieldRewardAmount, v)
	return u
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateRewardAmount() *InvitationUpsert {
	u.SetExcluded(invitation.FieldRewardAmount)
	return u
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *InvitationUpsert) AddRewardAmount(v float64) *InvitationUpsert {
	u.Add(invitation.FieldRewardAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *InvitationUpsert) SetStatus(v string) *InvitationUpsert {
	u.Set(invitation.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateStatus() *InvitationUpsert {
	u.SetExcluded(invitation.FieldStatus)
	return u
}

// SetConfirmedBy sets the "confirmed_by" field.
func (u *InvitationUpsert) SetConfirmedBy(v int64) *InvitationUpsert {
	u.Set(invitation.FieldConfirmedBy, v)
	return u
}

// UpdateConfirmedBy sets the "confirmed_by" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateConfirmedBy() *InvitationUpsert {
	u.SetExcluded(invitation.FieldConfirmedBy)
	return u
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (u *InvitationUpsert) ClearConfirmedBy() *InvitationUpsert {
	u.SetNull(invitation.FieldConfirmedBy)
	return u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (u *InvitationUpsert) SetConfirmedAt(v time.Time) *InvitationUpsert {
	u.Set(invitation.FieldConfirmedAt, v)
	return u
}

// UpdateConfirmedAt sets the "confirmed_at" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateConfirmedAt() *InvitationUpsert {
	u.SetExcluded(invitation.FieldConfirmedAt)
	return u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (u *InvitationUpsert) ClearConfirmedAt() *InvitationUpsert {
	u.SetNull(invitation.FieldConfirmedAt)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *InvitationUpsert) SetCreatedAt(v time.Time) *InvitationUpsert {
	u.Set(invitation.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateCreatedAt() *InvitationUpsert {
	u.SetExcluded(invitation.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Invitation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvitationUpsertOne) UpdateNewValues() *InvitationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invitation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvitationUpsertOne) Ignore() *InvitationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvitationUpsertOne) DoNothing() *InvitationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvitationCreate.OnConflict
// documentation for more info.
func (u *InvitationUpsertOne) Update(set func(*InvitationUpsert)) *InvitationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvitationUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterID sets the "inviter_id" field.
func (u *InvitationUpsertOne) SetInviterID(v int64) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetInviterID(v)
	})
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateInviterID() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateInviterID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *InvitationUpsertOne) SetInviteeID(v int64) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateInviteeID() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateInviteeID()
	})
}

// SetInviteCode sets the "invite_code" field.
func (u *InvitationUpsertOne) SetInviteCode(v string) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetInviteCode(v)
	})
}

// UpdateInviteCode sets the "invite_code" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateInviteCode() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateInviteCode()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *InvitationUpsertOne) SetRewardAmount(v float64) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *InvitationUpsertOne) AddRewardAmount(v float64) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateRewardAmount() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetStatus sets the "status" field.
func (u *InvitationUpsertOne) SetStatus(v string) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateStatus() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateStatus()
	})
}

// SetConfirmedBy sets the "confirmed_by" field.
func (u *InvitationUpsertOne) SetConfirmedBy(v int64) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetConfirmedBy(v)
	})
}

// UpdateConfirmedBy sets the "confirmed_by" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateConfirmedBy() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateConfirmedBy()
	})
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (u *InvitationUpsertOne) ClearConfirmedBy() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.ClearConfirmedBy()
	})
}

// SetConfirmedAt sets the "confirmed_at" field.
func (u *InvitationUpsertOne) SetConfirmedAt(v time.Time) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetConfirmedAt(v)
	})
}

// UpdateConfirmedAt sets the "confirmed_at" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateConfirmedAt() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateConfirmedAt()
	})
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (u *InvitationUpsertOne) ClearConfirmedAt() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.ClearConfirmedAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *InvitationUpsertOne) SetCreatedAt(v time.Time) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateCreatedAt() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *InvitationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvitationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvitationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvitationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvitationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvitationCreateBulk is the builder for creating many Invitation entities in bulk.
type InvitationCreateBulk struct {
	config
	err      error
	builders []*InvitationCreate
	conflict []sql.ConflictOption
}

// Save creates the Invitation entities in the database.
func (_c *InvitationCreateBulk) Save(ctx context.Context) ([]*Invitation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Invitation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvitationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvitationCreateBulk) SaveX(ctx context.Context) []*Invitation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvitationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvitationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invitation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvitationUpsert) {
//			SetInviterID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvitationCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvitationUpsertBulk {
	_c.conflict = opts
	return &InvitationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invitation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvitationCreateBulk) OnConflictColumns(columns ...string) *InvitationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvitationUpsertBulk{
		create: _c,
	}
}

// InvitationUpsertBulk is the builder for "upsert"-ing
// a bulk of Invitation nodes.
type InvitationUpsertBulk struct {
	create *InvitationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Invitation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvitationUpsertBulk) UpdateNewValues() *InvitationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invitation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvitationUpsertBulk) Ignore() *InvitationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvitationUpsertBulk) DoNothing() *InvitationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvitationCreateBulk.OnConflict
// documentation for more info.
func (u *InvitationUpsertBulk) Update(set func(*InvitationUpsert)) *InvitationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvitationUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterID sets the "inviter_id" field.
func (u *InvitationUpsertBulk) SetInviterID(v int64) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetInviterID(v)
	})
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateInviterID() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateInviterID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *InvitationUpsertBulk) SetInviteeID(v int64) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateInviteeID() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateInviteeID()
	})
}

// SetInviteCode sets the "invite_code" field.
func (u *InvitationUpsertBulk) SetInviteCode(v string) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetInviteCode(v)
	})
}

// UpdateInviteCode sets the "invite_code" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateInviteCode() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateInviteCode()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *InvitationUpsertBulk) SetRewardAmount(v float64) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *InvitationUpsertBulk) AddRewardAmount(v float64) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateRewardAmount() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetStatus sets the "status" field.
func (u *InvitationUpsertBulk) SetStatus(v string) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateStatus() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateStatus()
	})
}

// SetConfirmedBy sets the "confirmed_by" field.
func (u *InvitationUpsertBulk) SetConfirmedBy(v int64) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetConfirmedBy(v)
	})
}

// UpdateConfirmedBy sets the "confirmed_by" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateConfirmedBy() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateConfirmedBy()
	})
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (u *InvitationUpsertBulk) ClearConfirmedBy() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.ClearConfirmedBy()
	})
}

// SetConfirmedAt sets the "confirmed_at" field.
func (u *InvitationUpsertBulk) SetConfirmedAt(v time.Time) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetConfirmedAt(v)
	})
}

// UpdateConfirmedAt sets the "confirmed_at" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateConfirmedAt() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateConfirmedAt()
	})
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (u *InvitationUpsertBulk) ClearConfirmedAt() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.ClearConfirmedAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *InvitationUpsertBulk) SetCreatedAt(v time.Time) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateCreatedAt() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *InvitationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvitationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvitationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvitationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
