// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invitation"
	"github.com/Wei-Shaw/sub2api/ent/invitelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InviteLogCreate is the builder for creating a InviteLog entity.
type InviteLogCreate struct {
	config
	mutation *InviteLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInviteID sets the "invite_id" field.
func (_c *InviteLogCreate) SetInviteID(v int64) *InviteLogCreate {
	_c.mutation.SetInviteID(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *InviteLogCreate) SetAction(v string) *InviteLogCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetInviterID sets the "inviter_id" field.
func (_c *InviteLogCreate) SetInviterID(v int64) *InviteLogCreate {
	_c.mutation.SetInviterID(v)
	return _c
}

// SetInviteeID sets the "invitee_id" field.
func (_c *InviteLogCreate) SetInviteeID(v int64) *InviteLogCreate {
	_c.mutation.SetInviteeID(v)
	return _c
}

// SetAdminID sets the "admin_id" field.
func (_c *InviteLogCreate) SetAdminID(v int64) *InviteLogCreate {
	_c.mutation.SetAdminID(v)
	return _c
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_c *InviteLogCreate) SetNillableAdminID(v *int64) *InviteLogCreate {
	if v != nil {
		_c.SetAdminID(*v)
	}
	return _c
}

// SetRewardAmount sets the "reward_amount" field.
func (_c *InviteLogCreate) SetRewardAmount(v float64) *InviteLogCreate {
	_c.mutation.SetRewardAmount(v)
	return _c
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_c *InviteLogCreate) SetNillableRewardAmount(v *float64) *InviteLogCreate {
	if v != nil {
		_c.SetRewardAmount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InviteLogCreate) SetCreatedAt(v time.Time) *InviteLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InviteLogCreate) SetNillableCreatedAt(v *time.Time) *InviteLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetInvite sets the "invite" edge to the Invitation entity.
func (_c *InviteLogCreate) SetInvite(v *Invitation) *InviteLogCreate {
	return _c.SetInviteID(v.ID)
}

// SetInviter sets the "inviter" edge to the User entity.
func (_c *InviteLogCreate) SetInviter(v *User) *InviteLogCreate {
	return _c.SetInviterID(v.ID)
}

// SetInvitee sets the "invitee" edge to the User entity.
func (_c *InviteLogCreate) SetInvitee(v *User) *InviteLogCreate {
	return _c.SetInviteeID(v.ID)
}

// SetAdmin sets the "admin" edge to the User entity.
func (_c *InviteLogCreate) SetAdmin(v *User) *InviteLogCreate {
	return _c.SetAdminID(v.ID)
}

// Mutation returns the InviteLogMutation object of the builder.
func (_c *InviteLogCreate) Mutation() *InviteLogMutation {
	return _c.mutation
}

// Save creates the InviteLog in the database.
func (_c *InviteLogCreate) Save(ctx context.Context) (*InviteLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InviteLogCreate) SaveX(ctx context.Context) *InviteLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InviteLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InviteLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InviteLogCreate) defaults() {
	if _, ok := _c.mutation.RewardAmount(); !ok {
		v := invitelog.DefaultRewardAmount
		_c.mutation.SetRewardAmount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invitelog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InviteLogCreate) check() error {
	if _, ok := _c.mutation.InviteID(); !ok {
		return &ValidationError{Name: "invite_id", err: errors.New(`ent: missing required field "InviteLog.invite_id"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "InviteLog.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := invitelog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "InviteLog.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InviterID(); !ok {
		return &ValidationError{Name: "inviter_id", err: errors.New(`ent: missing required field "InviteLog.inviter_id"`)}
	}
	if _, ok := _c.mutation.InviteeID(); !ok {
		return &ValidationError{Name: "invitee_id", err: errors.New(`ent: missing required field "InviteLog.invitee_id"`)}
	}
	if _, ok := _c.mutation.RewardAmount(); !ok {
		return &ValidationError{Name: "reward_amount", err: errors.New(`ent: missing required field "InviteLog.reward_amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InviteLog.created_at"`)}
	}
	if len(_c.mutation.InviteIDs()) == 0 {
		return &ValidationError{Name: "invite", err: errors.New(`ent: missing required edge "InviteLog.invite"`)}
	}
	if len(_c.mutation.InviterIDs()) == 0 {
		return &ValidationError{Name: "inviter", err: errors.New(`ent: missing required edge "InviteLog.inviter"`)}
	}
	if len(_c.mutation.InviteeIDs()) == 0 {
		return &ValidationError{Name: "invitee", err: errors.New(`ent: missing required edge "InviteLog.invitee"`)}
	}
	return nil
}

func (_c *InviteLogCreate) sqlSave(ctx context.Context) (*InviteLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InviteLogCreate) createSpec() (*InviteLog, *sqlgraph.CreateSpec) {
	var (
		_node = &InviteLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invitelog.Table, sqlgraph.NewFieldSpec(invitelog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(invitelog.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.RewardAmount(); ok {
		_spec.SetField(invitelog.FieldRewardAmount, field.TypeFloat64, value)
		_node.RewardAmount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invitelog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.InviteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.InviteTable,
			Columns: []string{invitelog.InviteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InviteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InviterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.InviterTable,
			Columns: []string{invitelog.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InviterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InviteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.InviteeTable,
			Columns: []string{invitelog.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InviteeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitelog.AdminTable,
			Columns: []string{invitelog.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AdminID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InviteLog.Create().
//		SetInviteID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InviteLogUpsert) {
//			SetInviteID(v+v).
//		}).
//		Exec(ctx)
func (_c *InviteLogCreate) OnConflict(opts ...sql.ConflictOption) *InviteLogUpsertOne {
	_c.conflict = opts
	return &InviteLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InviteLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InviteLogCreate) OnConflictColumns(columns ...string) *InviteLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InviteLogUpsertOne{
		create: _c,
	}
}

type (
	// InviteLogUpsertOne is the builder for "upsert"-ing
	//  one InviteLog node.
	InviteLogUpsertOne struct {
		create *InviteLogCreate
	}

	// InviteLogUpsert is the "OnConflict" setter.
	InviteLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetInviteID sets the "invite_id" field.
func (u *InviteLogUpsert) SetInviteID(v int64) *InviteLogUpsert {
	u.Set(invitelog.FieldInviteID, v)
	return u
}

// UpdateInviteID sets the "invite_id" field to the value that was provided on create.
func (u *InviteLogUpsert) UpdateInviteID() *InviteLogUpsert {
	u.SetExcluded(invitelog.FieldInviteID)
	return u
}

// SetAction sets the "action" field.
func (u *InviteLogUpsert) SetAction(v string) *InviteLogUpsert {
	u.Set(invitelog.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *InviteLogUpsert) UpdateAction() *InviteLogUpsert {
	u.SetExcluded(invitelog.FieldAction)
	return u
}

// SetInviterID sets the "inviter_id" field.
func (u *InviteLogUpsert) SetInviterID(v int64) *InviteLogUpsert {
	u.Set(invitelog.FieldInviterID, v)
	return u
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *InviteLogUpsert) UpdateInviterID() *InviteLogUpsert {
	u.SetExcluded(invitelog.FieldInviterID)
	return u
}

// SetInviteeID sets the "invitee_id" field.
func (u *InviteLogUpsert) SetInviteeID(v int64) *InviteLogUpsert {
	u.Set(invitelog.FieldInviteeID, v)
	return u
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *InviteLogUpsert) UpdateInviteeID() *InviteLogUpsert {
	u.SetExcluded(invitelog.FieldInviteeID)
	return u
}

// SetAdminID sets the "admin_id" field.
func (u *InviteLogUpsert) SetAdminID(v int64) *InviteLogUpsert {
	u.Set(invitelog.FieldAdminID, v)
	return u
}

// UpdateAdminID sets the "admin_id" field to the value that was provided on create.
func (u *InviteLogUpsert) UpdateAdminID() *InviteLogUpsert {
	u.SetExcluded(invitelog.FieldAdminID)
	return u
}

// ClearAdminID clears the value of the "admin_id" field.
func (u *InviteLogUpsert) ClearAdminID() *InviteLogUpsert {
	u.SetNull(invitelog.FieldAdminID)
	return u
}

// SetRewardAmount sets the "reward_amount" field.
func (u *InviteLogUpsert) SetRewardAmount(v float64) *InviteLogUpsert {
	u.Set(invitelog.FieldRewardAmount, v)
	return u
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *InviteLogUpsert) UpdateRewardAmount() *InviteLogUpsert {
	u.SetExcluded(invitelog.FieldRewardAmount)
	return u
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *InviteLogUpsert) AddRewardAmount(v float64) *InviteLogUpsert {
	u.Add(invitelog.FieldRewardAmount, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *InviteLogUpsert) SetCreatedAt(v time.Time) *InviteLogUpsert {
	u.Set(invitelog.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *InviteLogUpsert) UpdateCreatedAt() *InviteLogUpsert {
	u.SetExcluded(invitelog.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InviteLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InviteLogUpsertOne) UpdateNewValues() *InviteLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InviteLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InviteLogUpsertOne) Ignore() *InviteLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InviteLogUpsertOne) DoNothing() *InviteLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InviteLogCreate.OnConflict
// documentation for more info.
func (u *InviteLogUpsertOne) Update(set func(*InviteLogUpsert)) *InviteLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InviteLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviteID sets the "invite_id" field.
func (u *InviteLogUpsertOne) SetInviteID(v int64) *InviteLogUpsertOne {
	return u.Update(func(s *InviteLogUpsert) {
		s.SetInviteID(v)
	})
}

// UpdateInviteID sets the "invite_id" field to the value that was provided on create.
func (u *InviteLogUpsertOne) UpdateInviteID() *InviteLogUpsertOne {
	return u.Update(func(s *InviteLogUpsert) {
		s.UpdateInviteID()
	})
}

// SetAction sets the "action" field.
func (u *InviteLogUpsertOne) SetAction(v string) *InviteLogUpsertOne {
	return u.Update(func(s *InviteLogUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *InviteLogUpsertOne) UpdateAction() *InviteLogUpsertOne {
	return u.Update(func(s *InviteLogUpsert) {
		s.UpdateAction()
	})
}

// SetInviterID sets the "inviter_id" field.
func (u *InviteLogUpsertOne) SetInviterID(v int64) *InviteLogUpsertOne {
	return u.Update(func(s *InviteLogUpsert) {
		s.SetInviterID(v)
	})
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *InviteLogUpsertOne) UpdateInviterID() *InviteLogUpsertOne {
	return u.Update(func(s *InviteLogUpsert) {
		s.UpdateInviterID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *InviteLogUpsertOne) SetInviteeID(v int64) *InviteLogUpsertOne {
	return u.Update(func(s *InviteLogUpsert) {
		s.SetInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *InviteLogUpsertOne) UpdateInviteeID() *InviteLogUpsertOne {
	return u.Update(func(s *InviteLogUpsert) {
		s.UpdateInviteeID()
	})
}

// SetAdminID sets the "admin_id" field.
func (u *InviteLogUpsertOne) SetAdminID(v int64) *InviteLogUpsertOne {
	return u.Update(func(s *InviteLogUpsert) {
		s.SetAdminID(v)
	})
}

// UpdateAdminID sets the "admin_id" field to the value that was provided on create.
func (u *InviteLogUpsertOne) UpdateAdminID() *InviteLogUpsertOne {
	return u.Update(func(s *InviteLogUpsert) {
		s.UpdateAdminID()
	})
}

// ClearAdminID clears the value of the "admin_id" field.
func (u *InviteLogUpsertOne) ClearAdminID() *InviteLogUpsertOne {
	return u.Update(func(s *InviteLogUpsert) {
		s.ClearAdminID()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *InviteLogUpsertOne) SetRewardAmount(v float64) *InviteLogUpsertOne {
	return u.Update(func(s *InviteLogUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *InviteLogUpsertOne) AddRewardAmount(v float64) *InviteLogUpsertOne {
	return u.Update(func(s *InviteLogUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *InviteLogUpsertOne) UpdateRewardAmount() *InviteLogUpsertOne {
	return u.Update(func(s *InviteLogUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *InviteLogUpsertOne) SetCreatedAt(v time.Time) *InviteLogUpsertOne {
	return u.Update(func(s *InviteLogUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *InviteLogUpsertOne) UpdateCreatedAt() *InviteLogUpsertOne {
	return u.Update(func(s *InviteLogUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *InviteLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InviteLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InviteLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InviteLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InviteLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InviteLogCreateBulk is the builder for creating many InviteLog entities in bulk.
type InviteLogCreateBulk struct {
	config
	err      error
	builders []*InviteLogCreate
	conflict []sql.ConflictOption
}

// Save creates the InviteLog entities in the database.
func (_c *InviteLogCreateBulk) Save(ctx context.Context) ([]*InviteLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InviteLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InviteLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InviteLogCreateBulk) SaveX(ctx context.Context) []*InviteLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InviteLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InviteLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InviteLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InviteLogUpsert) {
//			SetInviteID(v+v).
//		}).
//		Exec(ctx)
func (_c *InviteLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *InviteLogUpsertBulk {
	_c.conflict = opts
	return &InviteLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InviteLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InviteLogCreateBulk) OnConflictColumns(columns ...string) *InviteLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InviteLogUpsertBulk{
		create: _c,
	}
}

// InviteLogUpsertBulk is the builder for "upsert"-ing
// a bulk of InviteLog nodes.
type InviteLogUpsertBulk struct {
	create *InviteLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InviteLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InviteLogUpsertBulk) UpdateNewValues() *InviteLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InviteLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InviteLogUpsertBulk) Ignore() *InviteLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InviteLogUpsertBulk) DoNothing() *InviteLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InviteLogCreateBulk.OnConflict
// documentation for more info.
func (u *InviteLogUpsertBulk) Update(set func(*InviteLogUpsert)) *InviteLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InviteLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviteID sets the "invite_id" field.
func (u *InviteLogUpsertBulk) SetInviteID(v int64) *InviteLogUpsertBulk {
	return u.Update(func(s *InviteLogUpsert) {
		s.SetInviteID(v)
	})
}

// UpdateInviteID sets the "invite_id" field to the value that was provided on create.
func (u *InviteLogUpsertBulk) UpdateInviteID() *InviteLogUpsertBulk {
	return u.Update(func(s *InviteLogUpsert) {
		s.UpdateInviteID()
	})
}

// SetAction sets the "action" field.
func (u *InviteLogUpsertBulk) SetAction(v string) *InviteLogUpsertBulk {
	return u.Update(func(s *InviteLogUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *InviteLogUpsertBulk) UpdateAction() *InviteLogUpsertBulk {
	return u.Update(func(s *InviteLogUpsert) {
		s.UpdateAction()
	})
}

// SetInviterID sets the "inviter_id" field.
func (u *InviteLogUpsertBulk) SetInviterID(v int64) *InviteLogUpsertBulk {
	return u.Update(func(s *InviteLogUpsert) {
		s.SetInviterID(v)
	})
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *InviteLogUpsertBulk) UpdateInviterID() *InviteLogUpsertBulk {
	return u.Update(func(s *InviteLogUpsert) {
		s.UpdateInviterID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *InviteLogUpsertBulk) SetInviteeID(v int64) *InviteLogUpsertBulk {
	return u.Update(func(s *InviteLogUpsert) {
		s.SetInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *InviteLogUpsertBulk) UpdateInviteeID() *InviteLogUpsertBulk {
	return u.Update(func(s *InviteLogUpsert) {
		s.UpdateInviteeID()
	})
}

// SetAdminID sets the "admin_id" field.
func (u *InviteLogUpsertBulk) SetAdminID(v int64) *InviteLogUpsertBulk {
	return u.Update(func(s *InviteLogUpsert) {
		s.SetAdminID(v)
	})
}

// UpdateAdminID sets the "admin_id" field to the value that was provided on create.
func (u *InviteLogUpsertBulk) UpdateAdminID() *InviteLogUpsertBulk {
	return u.Update(func(s *InviteLogUpsert) {
		s.UpdateAdminID()
	})
}

// ClearAdminID clears the value of the "admin_id" field.
func (u *InviteLogUpsertBulk) ClearAdminID() *InviteLogUpsertBulk {
	return u.Update(func(s *InviteLogUpsert) {
		s.ClearAdminID()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *InviteLogUpsertBulk) SetRewardAmount(v float64) *InviteLogUpsertBulk {
	return u.Update(func(s *InviteLogUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *InviteLogUpsertBulk) AddRewardAmount(v float64) *InviteLogUpsertBulk {
	return u.Update(func(s *InviteLogUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *InviteLogUpsertBulk) UpdateRewardAmount() *InviteLogUpsertBulk {
	return u.Update(func(s *InviteLogUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *InviteLogUpsertBulk) SetCreatedAt(v time.Time) *InviteLogUpsertBulk {
	return u.Update(func(s *InviteLogUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *InviteLogUpsertBulk) UpdateCreatedAt() *InviteLogUpsertBulk {
	return u.Update(func(s *InviteLogUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *InviteLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InviteLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InviteLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InviteLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
