// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/plan"
)

// Plan is the model entity for the Plan schema.
type Plan struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 套餐标题
	Title string `json:"title,omitempty"`
	// 套餐描述
	Description *string `json:"description,omitempty"`
	// 套餐价格（CNY）
	Price float64 `json:"price,omitempty"`
	// 分组名称
	GroupName string `json:"group_name,omitempty"`
	// 分组排序
	GroupSort int `json:"group_sort,omitempty"`
	// 每日额度
	DailyQuota float64 `json:"daily_quota,omitempty"`
	// 总额度
	TotalQuota float64 `json:"total_quota,omitempty"`
	// 购买二维码URL
	PurchaseQrURL *string `json:"purchase_qr_url,omitempty"`
	// 是否启用
	Enabled bool `json:"enabled,omitempty"`
	// 排序
	SortOrder int `json:"sort_order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Plan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case plan.FieldEnabled:
			values[i] = new(sql.NullBool)
		case plan.FieldPrice, plan.FieldDailyQuota, plan.FieldTotalQuota:
			values[i] = new(sql.NullFloat64)
		case plan.FieldID, plan.FieldGroupSort, plan.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case plan.FieldTitle, plan.FieldDescription, plan.FieldGroupName, plan.FieldPurchaseQrURL:
			values[i] = new(sql.NullString)
		case plan.FieldCreatedAt, plan.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Plan fields.
func (_m *Plan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case plan.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case plan.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case plan.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case plan.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.Float64
			}
		case plan.FieldGroupName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_name", values[i])
			} else if value.Valid {
				_m.GroupName = value.String
			}
		case plan.FieldGroupSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_sort", values[i])
			} else if value.Valid {
				_m.GroupSort = int(value.Int64)
			}
		case plan.FieldDailyQuota:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_quota", values[i])
			} else if value.Valid {
				_m.DailyQuota = value.Float64
			}
		case plan.FieldTotalQuota:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_quota", values[i])
			} else if value.Valid {
				_m.TotalQuota = value.Float64
			}
		case plan.FieldPurchaseQrURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_qr_url", values[i])
			} else if value.Valid {
				_m.PurchaseQrURL = new(string)
				*_m.PurchaseQrURL = value.String
			}
		case plan.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case plan.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case plan.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case plan.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Plan.
// This includes values selected through modifiers, order, etc.
func (_m *Plan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Plan.
// Note that you need to call Plan.Unwrap() before calling this method if this Plan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Plan) Update() *PlanUpdateOne {
	return NewPlanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Plan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Plan) Unwrap() *Plan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Plan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Plan) String() string {
	var builder strings.Builder
	builder.WriteString("Plan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	builder.WriteString("group_name=")
	builder.WriteString(_m.GroupName)
	builder.WriteString(", ")
	builder.WriteString("group_sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupSort))
	builder.WriteString(", ")
	builder.WriteString("daily_quota=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyQuota))
	builder.WriteString(", ")
	builder.WriteString("total_quota=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalQuota))
	builder.WriteString(", ")
	if v := _m.PurchaseQrURL; v != nil {
		builder.WriteString("purchase_qr_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Plans is a parsable slice of Plan.
type Plans []*Plan
