// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/plan"
)

// PlanCreate is the builder for creating a Plan entity.
type PlanCreate struct {
	config
	mutation *PlanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTitle sets the "title" field.
func (_c *PlanCreate) SetTitle(v string) *PlanCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PlanCreate) SetDescription(v string) *PlanCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PlanCreate) SetNillableDescription(v *string) *PlanCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *PlanCreate) SetPrice(v float64) *PlanCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_c *PlanCreate) SetNillablePrice(v *float64) *PlanCreate {
	if v != nil {
		_c.SetPrice(*v)
	}
	return _c
}

// SetGroupName sets the "group_name" field.
func (_c *PlanCreate) SetGroupName(v string) *PlanCreate {
	_c.mutation.SetGroupName(v)
	return _c
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_c *PlanCreate) SetNillableGroupName(v *string) *PlanCreate {
	if v != nil {
		_c.SetGroupName(*v)
	}
	return _c
}

// SetGroupSort sets the "group_sort" field.
func (_c *PlanCreate) SetGroupSort(v int) *PlanCreate {
	_c.mutation.SetGroupSort(v)
	return _c
}

// SetNillableGroupSort sets the "group_sort" field if the given value is not nil.
func (_c *PlanCreate) SetNillableGroupSort(v *int) *PlanCreate {
	if v != nil {
		_c.SetGroupSort(*v)
	}
	return _c
}

// SetDailyQuota sets the "daily_quota" field.
func (_c *PlanCreate) SetDailyQuota(v float64) *PlanCreate {
	_c.mutation.SetDailyQuota(v)
	return _c
}

// SetNillableDailyQuota sets the "daily_quota" field if the given value is not nil.
func (_c *PlanCreate) SetNillableDailyQuota(v *float64) *PlanCreate {
	if v != nil {
		_c.SetDailyQuota(*v)
	}
	return _c
}

// SetTotalQuota sets the "total_quota" field.
func (_c *PlanCreate) SetTotalQuota(v float64) *PlanCreate {
	_c.mutation.SetTotalQuota(v)
	return _c
}

// SetNillableTotalQuota sets the "total_quota" field if the given value is not nil.
func (_c *PlanCreate) SetNillableTotalQuota(v *float64) *PlanCreate {
	if v != nil {
		_c.SetTotalQuota(*v)
	}
	return _c
}

// SetPurchaseQrURL sets the "purchase_qr_url" field.
func (_c *PlanCreate) SetPurchaseQrURL(v string) *PlanCreate {
	_c.mutation.SetPurchaseQrURL(v)
	return _c
}

// SetNillablePurchaseQrURL sets the "purchase_qr_url" field if the given value is not nil.
func (_c *PlanCreate) SetNillablePurchaseQrURL(v *string) *PlanCreate {
	if v != nil {
		_c.SetPurchaseQrURL(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *PlanCreate) SetEnabled(v bool) *PlanCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *PlanCreate) SetNillableEnabled(v *bool) *PlanCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *PlanCreate) SetSortOrder(v int) *PlanCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *PlanCreate) SetNillableSortOrder(v *int) *PlanCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlanCreate) SetCreatedAt(v time.Time) *PlanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlanCreate) SetNillableCreatedAt(v *time.Time) *PlanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PlanCreate) SetUpdatedAt(v time.Time) *PlanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PlanCreate) SetNillableUpdatedAt(v *time.Time) *PlanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the PlanMutation object of the builder.
func (_c *PlanCreate) Mutation() *PlanMutation {
	return _c.mutation
}

// Save creates the Plan in the database.
func (_c *PlanCreate) Save(ctx context.Context) (*Plan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlanCreate) SaveX(ctx context.Context) *Plan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlanCreate) defaults() {
	if _, ok := _c.mutation.Price(); !ok {
		v := plan.DefaultPrice
		_c.mutation.SetPrice(v)
	}
	if _, ok := _c.mutation.GroupName(); !ok {
		v := plan.DefaultGroupName
		_c.mutation.SetGroupName(v)
	}
	if _, ok := _c.mutation.GroupSort(); !ok {
		v := plan.DefaultGroupSort
		_c.mutation.SetGroupSort(v)
	}
	if _, ok := _c.mutation.DailyQuota(); !ok {
		v := plan.DefaultDailyQuota
		_c.mutation.SetDailyQuota(v)
	}
	if _, ok := _c.mutation.TotalQuota(); !ok {
		v := plan.DefaultTotalQuota
		_c.mutation.SetTotalQuota(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := plan.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := plan.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := plan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := plan.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlanCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Plan.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := plan.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Plan.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Plan.price"`)}
	}
	if _, ok := _c.mutation.GroupName(); !ok {
		return &ValidationError{Name: "group_name", err: errors.New(`ent: missing required field "Plan.group_name"`)}
	}
	if v, ok := _c.mutation.GroupName(); ok {
		if err := plan.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "Plan.group_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GroupSort(); !ok {
		return &ValidationError{Name: "group_sort", err: errors.New(`ent: missing required field "Plan.group_sort"`)}
	}
	if _, ok := _c.mutation.DailyQuota(); !ok {
		return &ValidationError{Name: "daily_quota", err: errors.New(`ent: missing required field "Plan.daily_quota"`)}
	}
	if _, ok := _c.mutation.TotalQuota(); !ok {
		return &ValidationError{Name: "total_quota", err: errors.New(`ent: missing required field "Plan.total_quota"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Plan.enabled"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "Plan.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Plan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Plan.updated_at"`)}
	}
	return nil
}

func (_c *PlanCreate) sqlSave(ctx context.Context) (*Plan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlanCreate) createSpec() (*Plan, *sqlgraph.CreateSpec) {
	var (
		_node = &Plan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(plan.Table, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(plan.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(plan.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(plan.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.GroupName(); ok {
		_spec.SetField(plan.FieldGroupName, field.TypeString, value)
		_node.GroupName = value
	}
	if value, ok := _c.mutation.GroupSort(); ok {
		_spec.SetField(plan.FieldGroupSort, field.TypeInt, value)
		_node.GroupSort = value
	}
	if value, ok := _c.mutation.DailyQuota(); ok {
		_spec.SetField(plan.FieldDailyQuota, field.TypeFloat64, value)
		_node.DailyQuota = value
	}
	if value, ok := _c.mutation.TotalQuota(); ok {
		_spec.SetField(plan.FieldTotalQuota, field.TypeFloat64, value)
		_node.TotalQuota = value
	}
	if value, ok := _c.mutation.PurchaseQrURL(); ok {
		_spec.SetField(plan.FieldPurchaseQrURL, field.TypeString, value)
		_node.PurchaseQrURL = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(plan.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(plan.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(plan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(plan.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Plan.Create().
//		SetTitle(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlanUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *PlanCreate) OnConflict(opts ...sql.ConflictOption) *PlanUpsertOne {
	_c.conflict = opts
	return &PlanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Plan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlanCreate) OnConflictColumns(columns ...string) *PlanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlanUpsertOne{
		create: _c,
	}
}

type (
	// PlanUpsertOne is the builder for "upsert"-ing
	//  one Plan node.
	PlanUpsertOne struct {
		create *PlanCreate
	}

	// PlanUpsert is the "OnConflict" setter.
	PlanUpsert struct {
		*sql.UpdateSet
	}
)

// SetTitle sets the "title" field.
func (u *PlanUpsert) SetTitle(v string) *PlanUpsert {
	u.Set(plan.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PlanUpsert) UpdateTitle() *PlanUpsert {
	u.SetExcluded(plan.FieldTitle)
	return u
}

// SetDescription sets the "description" field.
func (u *PlanUpsert) SetDescription(v string) *PlanUpsert {
	u.Set(plan.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PlanUpsert) UpdateDescription() *PlanUpsert {
	u.SetExcluded(plan.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *PlanUpsert) ClearDescription() *PlanUpsert {
	u.SetNull(plan.FieldDescription)
	return u
}

// SetPrice sets the "price" field.
func (u *PlanUpsert) SetPrice(v float64) *PlanUpsert {
	u.Set(plan.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *PlanUpsert) UpdatePrice() *PlanUpsert {
	u.SetExcluded(plan.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *PlanUpsert) AddPrice(v float64) *PlanUpsert {
	u.Add(plan.FieldPrice, v)
	return u
}

// SetGroupName sets the "group_name" field.
func (u *PlanUpsert) SetGroupName(v string) *PlanUpsert {
	u.Set(plan.FieldGroupName, v)
	return u
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *PlanUpsert) UpdateGroupName() *PlanUpsert {
	u.SetExcluded(plan.FieldGroupName)
	return u
}

// SetGroupSort sets the "group_sort" field.
func (u *PlanUpsert) SetGroupSort(v int) *PlanUpsert {
	u.Set(plan.FieldGroupSort, v)
	return u
}

// UpdateGroupSort sets the "group_sort" field to the value that was provided on create.
func (u *PlanUpsert) UpdateGroupSort() *PlanUpsert {
	u.SetExcluded(plan.FieldGroupSort)
	return u
}

// AddGroupSort adds v to the "group_sort" field.
func (u *PlanUpsert) AddGroupSort(v int) *PlanUpsert {
	u.Add(plan.FieldGroupSort, v)
	return u
}

// SetDailyQuota sets the "daily_quota" field.
func (u *PlanUpsert) SetDailyQuota(v float64) *PlanUpsert {
	u.Set(plan.FieldDailyQuota, v)
	return u
}

// UpdateDailyQuota sets the "daily_quota" field to the value that was provided on create.
func (u *PlanUpsert) UpdateDailyQuota() *PlanUpsert {
	u.SetExcluded(plan.FieldDailyQuota)
	return u
}

// AddDailyQuota adds v to the "daily_quota" field.
func (u *PlanUpsert) AddDailyQuota(v float64) *PlanUpsert {
	u.Add(plan.FieldDailyQuota, v)
	return u
}

// SetTotalQuota sets the "total_quota" field.
func (u *PlanUpsert) SetTotalQuota(v float64) *PlanUpsert {
	u.Set(plan.FieldTotalQuota, v)
	return u
}

// UpdateTotalQuota sets the "total_quota" field to the value that was provided on create.
func (u *PlanUpsert) UpdateTotalQuota() *PlanUpsert {
	u.SetExcluded(plan.FieldTotalQuota)
	return u
}

// AddTotalQuota adds v to the "total_quota" field.
func (u *PlanUpsert) AddTotalQuota(v float64) *PlanUpsert {
	u.Add(plan.FieldTotalQuota, v)
	return u
}

// SetPurchaseQrURL sets the "purchase_qr_url" field.
func (u *PlanUpsert) SetPurchaseQrURL(v string) *PlanUpsert {
	u.Set(plan.FieldPurchaseQrURL, v)
	return u
}

// UpdatePurchaseQrURL sets the "purchase_qr_url" field to the value that was provided on create.
func (u *PlanUpsert) UpdatePurchaseQrURL() *PlanUpsert {
	u.SetExcluded(plan.FieldPurchaseQrURL)
	return u
}

// ClearPurchaseQrURL clears the value of the "purchase_qr_url" field.
func (u *PlanUpsert) ClearPurchaseQrURL() *PlanUpsert {
	u.SetNull(plan.FieldPurchaseQrURL)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *PlanUpsert) SetEnabled(v bool) *PlanUpsert {
	u.Set(plan.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PlanUpsert) UpdateEnabled() *PlanUpsert {
	u.SetExcluded(plan.FieldEnabled)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *PlanUpsert) SetSortOrder(v int) *PlanUpsert {
	u.Set(plan.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PlanUpsert) UpdateSortOrder() *PlanUpsert {
	u.SetExcluded(plan.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PlanUpsert) AddSortOrder(v int) *PlanUpsert {
	u.Add(plan.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlanUpsert) SetUpdatedAt(v time.Time) *PlanUpsert {
	u.Set(plan.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlanUpsert) UpdateUpdatedAt() *PlanUpsert {
	u.SetExcluded(plan.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Plan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PlanUpsertOne) UpdateNewValues() *PlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(plan.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Plan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PlanUpsertOne) Ignore() *PlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlanUpsertOne) DoNothing() *PlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlanCreate.OnConflict
// documentation for more info.
func (u *PlanUpsertOne) Update(set func(*PlanUpsert)) *PlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *PlanUpsertOne) SetTitle(v string) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateTitle() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *PlanUpsertOne) SetDescription(v string) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateDescription() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *PlanUpsertOne) ClearDescription() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.ClearDescription()
	})
}

// SetPrice sets the "price" field.
func (u *PlanUpsertOne) SetPrice(v float64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *PlanUpsertOne) AddPrice(v float64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdatePrice() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdatePrice()
	})
}

// SetGroupName sets the "group_name" field.
func (u *PlanUpsertOne) SetGroupName(v string) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateGroupName() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateGroupName()
	})
}

// SetGroupSort sets the "group_sort" field.
func (u *PlanUpsertOne) SetGroupSort(v int) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetGroupSort(v)
	})
}

// AddGroupSort adds v to the "group_sort" field.
func (u *PlanUpsertOne) AddGroupSort(v int) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddGroupSort(v)
	})
}

// UpdateGroupSort sets the "group_sort" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateGroupSort() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateGroupSort()
	})
}

// SetDailyQuota sets the "daily_quota" field.
func (u *PlanUpsertOne) SetDailyQuota(v float64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetDailyQuota(v)
	})
}

// AddDailyQuota adds v to the "daily_quota" field.
func (u *PlanUpsertOne) AddDailyQuota(v float64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddDailyQuota(v)
	})
}

// UpdateDailyQuota sets the "daily_quota" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateDailyQuota() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateDailyQuota()
	})
}

// SetTotalQuota sets the "total_quota" field.
func (u *PlanUpsertOne) SetTotalQuota(v float64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetTotalQuota(v)
	})
}

// AddTotalQuota adds v to the "total_quota" field.
func (u *PlanUpsertOne) AddTotalQuota(v float64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddTotalQuota(v)
	})
}

// UpdateTotalQuota sets the "total_quota" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateTotalQuota() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateTotalQuota()
	})
}

// SetPurchaseQrURL sets the "purchase_qr_url" field.
func (u *PlanUpsertOne) SetPurchaseQrURL(v string) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetPurchaseQrURL(v)
	})
}

// UpdatePurchaseQrURL sets the "purchase_qr_url" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdatePurchaseQrURL() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdatePurchaseQrURL()
	})
}

// ClearPurchaseQrURL clears the value of the "purchase_qr_url" field.
func (u *PlanUpsertOne) ClearPurchaseQrURL() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.ClearPurchaseQrURL()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PlanUpsertOne) SetEnabled(v bool) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateEnabled() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *PlanUpsertOne) SetSortOrder(v int) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PlanUpsertOne) AddSortOrder(v int) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateSortOrder() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlanUpsertOne) SetUpdatedAt(v time.Time) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateUpdatedAt() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PlanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PlanUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PlanUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PlanCreateBulk is the builder for creating many Plan entities in bulk.
type PlanCreateBulk struct {
	config
	err      error
	builders []*PlanCreate
	conflict []sql.ConflictOption
}

// Save creates the Plan entities in the database.
func (_c *PlanCreateBulk) Save(ctx context.Context) ([]*Plan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Plan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlanCreateBulk) SaveX(ctx context.Context) []*Plan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Plan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlanUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *PlanCreateBulk) OnConflict(opts ...sql.ConflictOption) *PlanUpsertBulk {
	_c.conflict = opts
	return &PlanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Plan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlanCreateBulk) OnConflictColumns(columns ...string) *PlanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlanUpsertBulk{
		create: _c,
	}
}

// PlanUpsertBulk is the builder for "upsert"-ing
// a bulk of Plan nodes.
type PlanUpsertBulk struct {
	create *PlanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Plan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PlanUpsertBulk) UpdateNewValues() *PlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(plan.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Plan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PlanUpsertBulk) Ignore() *PlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlanUpsertBulk) DoNothing() *PlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlanCreateBulk.OnConflict
// documentation for more info.
func (u *PlanUpsertBulk) Update(set func(*PlanUpsert)) *PlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *PlanUpsertBulk) SetTitle(v string) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateTitle() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *PlanUpsertBulk) SetDescription(v string) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateDescription() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *PlanUpsertBulk) ClearDescription() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.ClearDescription()
	})
}

// SetPrice sets the "price" field.
func (u *PlanUpsertBulk) SetPrice(v float64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *PlanUpsertBulk) AddPrice(v float64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdatePrice() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdatePrice()
	})
}

// SetGroupName sets the "group_name" field.
func (u *PlanUpsertBulk) SetGroupName(v string) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateGroupName() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateGroupName()
	})
}

// SetGroupSort sets the "group_sort" field.
func (u *PlanUpsertBulk) SetGroupSort(v int) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetGroupSort(v)
	})
}

// AddGroupSort adds v to the "group_sort" field.
func (u *PlanUpsertBulk) AddGroupSort(v int) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddGroupSort(v)
	})
}

// UpdateGroupSort sets the "group_sort" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateGroupSort() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateGroupSort()
	})
}

// SetDailyQuota sets the "daily_quota" field.
func (u *PlanUpsertBulk) SetDailyQuota(v float64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetDailyQuota(v)
	})
}

// AddDailyQuota adds v to the "daily_quota" field.
func (u *PlanUpsertBulk) AddDailyQuota(v float64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddDailyQuota(v)
	})
}

// UpdateDailyQuota sets the "daily_quota" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateDailyQuota() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateDailyQuota()
	})
}

// SetTotalQuota sets the "total_quota" field.
func (u *PlanUpsertBulk) SetTotalQuota(v float64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetTotalQuota(v)
	})
}

// AddTotalQuota adds v to the "total_quota" field.
func (u *PlanUpsertBulk) AddTotalQuota(v float64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddTotalQuota(v)
	})
}

// UpdateTotalQuota sets the "total_quota" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateTotalQuota() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateTotalQuota()
	})
}

// SetPurchaseQrURL sets the "purchase_qr_url" field.
func (u *PlanUpsertBulk) SetPurchaseQrURL(v string) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetPurchaseQrURL(v)
	})
}

// UpdatePurchaseQrURL sets the "purchase_qr_url" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdatePurchaseQrURL() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdatePurchaseQrURL()
	})
}

// ClearPurchaseQrURL clears the value of the "purchase_qr_url" field.
func (u *PlanUpsertBulk) ClearPurchaseQrURL() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.ClearPurchaseQrURL()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PlanUpsertBulk) SetEnabled(v bool) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateEnabled() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *PlanUpsertBulk) SetSortOrder(v int) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PlanUpsertBulk) AddSortOrder(v int) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateSortOrder() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlanUpsertBulk) SetUpdatedAt(v time.Time) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateUpdatedAt() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PlanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PlanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
