// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/plan"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PlanUpdate is the builder for updating Plan entities.
type PlanUpdate struct {
	config
	hooks    []Hook
	mutation *PlanMutation
}

// Where appends a list predicates to the PlanUpdate builder.
func (_u *PlanUpdate) Where(ps ...predicate.Plan) *PlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *PlanUpdate) SetTitle(v string) *PlanUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableTitle(v *string) *PlanUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PlanUpdate) SetDescription(v string) *PlanUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableDescription(v *string) *PlanUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PlanUpdate) ClearDescription() *PlanUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPrice sets the "price" field.
func (_u *PlanUpdate) SetPrice(v float64) *PlanUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PlanUpdate) SetNillablePrice(v *float64) *PlanUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *PlanUpdate) AddPrice(v float64) *PlanUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *PlanUpdate) SetGroupName(v string) *PlanUpdate {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableGroupName(v *string) *PlanUpdate {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// SetGroupSort sets the "group_sort" field.
func (_u *PlanUpdate) SetGroupSort(v int) *PlanUpdate {
	_u.mutation.ResetGroupSort()
	_u.mutation.SetGroupSort(v)
	return _u
}

// SetNillableGroupSort sets the "group_sort" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableGroupSort(v *int) *PlanUpdate {
	if v != nil {
		_u.SetGroupSort(*v)
	}
	return _u
}

// AddGroupSort adds value to the "group_sort" field.
func (_u *PlanUpdate) AddGroupSort(v int) *PlanUpdate {
	_u.mutation.AddGroupSort(v)
	return _u
}

// SetDailyQuota sets the "daily_quota" field.
func (_u *PlanUpdate) SetDailyQuota(v float64) *PlanUpdate {
	_u.mutation.ResetDailyQuota()
	_u.mutation.SetDailyQuota(v)
	return _u
}

// SetNillableDailyQuota sets the "daily_quota" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableDailyQuota(v *float64) *PlanUpdate {
	if v != nil {
		_u.SetDailyQuota(*v)
	}
	return _u
}

// AddDailyQuota adds value to the "daily_quota" field.
func (_u *PlanUpdate) AddDailyQuota(v float64) *PlanUpdate {
	_u.mutation.AddDailyQuota(v)
	return _u
}

// SetTotalQuota sets the "total_quota" field.
func (_u *PlanUpdate) SetTotalQuota(v float64) *PlanUpdate {
	_u.mutation.ResetTotalQuota()
	_u.mutation.SetTotalQuota(v)
	return _u
}

// SetNillableTotalQuota sets the "total_quota" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableTotalQuota(v *float64) *PlanUpdate {
	if v != nil {
		_u.SetTotalQuota(*v)
	}
	return _u
}

// AddTotalQuota adds value to the "total_quota" field.
func (_u *PlanUpdate) AddTotalQuota(v float64) *PlanUpdate {
	_u.mutation.AddTotalQuota(v)
	return _u
}

// SetPurchaseQrURL sets the "purchase_qr_url" field.
func (_u *PlanUpdate) SetPurchaseQrURL(v string) *PlanUpdate {
	_u.mutation.SetPurchaseQrURL(v)
	return _u
}

// SetNillablePurchaseQrURL sets the "purchase_qr_url" field if the given value is not nil.
func (_u *PlanUpdate) SetNillablePurchaseQrURL(v *string) *PlanUpdate {
	if v != nil {
		_u.SetPurchaseQrURL(*v)
	}
	return _u
}

// ClearPurchaseQrURL clears the value of the "purchase_qr_url" field.
func (_u *PlanUpdate) ClearPurchaseQrURL() *PlanUpdate {
	_u.mutation.ClearPurchaseQrURL()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PlanUpdate) SetEnabled(v bool) *PlanUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableEnabled(v *bool) *PlanUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *PlanUpdate) SetSortOrder(v int) *PlanUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableSortOrder(v *int) *PlanUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *PlanUpdate) AddSortOrder(v int) *PlanUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlanUpdate) SetUpdatedAt(v time.Time) *PlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PlanMutation object of the builder.
func (_u *PlanUpdate) Mutation() *PlanMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := plan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlanUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := plan.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Plan.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupName(); ok {
		if err := plan.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "Plan.group_name": %w`, err)}
		}
	}
	return nil
}

func (_u *PlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plan.Table, plan.Columns, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(plan.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(plan.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(plan.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(plan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(plan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(plan.FieldGroupName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupSort(); ok {
		_spec.SetField(plan.FieldGroupSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGroupSort(); ok {
		_spec.AddField(plan.FieldGroupSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DailyQuota(); ok {
		_spec.SetField(plan.FieldDailyQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyQuota(); ok {
		_spec.AddField(plan.FieldDailyQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalQuota(); ok {
		_spec.SetField(plan.FieldTotalQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalQuota(); ok {
		_spec.AddField(plan.FieldTotalQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PurchaseQrURL(); ok {
		_spec.SetField(plan.FieldPurchaseQrURL, field.TypeString, value)
	}
	if _u.mutation.PurchaseQrURLCleared() {
		_spec.ClearField(plan.FieldPurchaseQrURL, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(plan.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(plan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(plan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(plan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlanUpdateOne is the builder for updating a single Plan entity.
type PlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlanMutation
}

// SetTitle sets the "title" field.
func (_u *PlanUpdateOne) SetTitle(v string) *PlanUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableTitle(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PlanUpdateOne) SetDescription(v string) *PlanUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableDescription(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PlanUpdateOne) ClearDescription() *PlanUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPrice sets the "price" field.
func (_u *PlanUpdateOne) SetPrice(v float64) *PlanUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillablePrice(v *float64) *PlanUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *PlanUpdateOne) AddPrice(v float64) *PlanUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *PlanUpdateOne) SetGroupName(v string) *PlanUpdateOne {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableGroupName(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// SetGroupSort sets the "group_sort" field.
func (_u *PlanUpdateOne) SetGroupSort(v int) *PlanUpdateOne {
	_u.mutation.ResetGroupSort()
	_u.mutation.SetGroupSort(v)
	return _u
}

// SetNillableGroupSort sets the "group_sort" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableGroupSort(v *int) *PlanUpdateOne {
	if v != nil {
		_u.SetGroupSort(*v)
	}
	return _u
}

// AddGroupSort adds value to the "group_sort" field.
func (_u *PlanUpdateOne) AddGroupSort(v int) *PlanUpdateOne {
	_u.mutation.AddGroupSort(v)
	return _u
}

// SetDailyQuota sets the "daily_quota" field.
func (_u *PlanUpdateOne) SetDailyQuota(v float64) *PlanUpdateOne {
	_u.mutation.ResetDailyQuota()
	_u.mutation.SetDailyQuota(v)
	return _u
}

// SetNillableDailyQuota sets the "daily_quota" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableDailyQuota(v *float64) *PlanUpdateOne {
	if v != nil {
		_u.SetDailyQuota(*v)
	}
	return _u
}

// AddDailyQuota adds value to the "daily_quota" field.
func (_u *PlanUpdateOne) AddDailyQuota(v float64) *PlanUpdateOne {
	_u.mutation.AddDailyQuota(v)
	return _u
}

// SetTotalQuota sets the "total_quota" field.
func (_u *PlanUpdateOne) SetTotalQuota(v float64) *PlanUpdateOne {
	_u.mutation.ResetTotalQuota()
	_u.mutation.SetTotalQuota(v)
	return _u
}

// SetNillableTotalQuota sets the "total_quota" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableTotalQuota(v *float64) *PlanUpdateOne {
	if v != nil {
		_u.SetTotalQuota(*v)
	}
	return _u
}

// AddTotalQuota adds value to the "total_quota" field.
func (_u *PlanUpdateOne) AddTotalQuota(v float64) *PlanUpdateOne {
	_u.mutation.AddTotalQuota(v)
	return _u
}

// SetPurchaseQrURL sets the "purchase_qr_url" field.
func (_u *PlanUpdateOne) SetPurchaseQrURL(v string) *PlanUpdateOne {
	_u.mutation.SetPurchaseQrURL(v)
	return _u
}

// SetNillablePurchaseQrURL sets the "purchase_qr_url" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillablePurchaseQrURL(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetPurchaseQrURL(*v)
	}
	return _u
}

// ClearPurchaseQrURL clears the value of the "purchase_qr_url" field.
func (_u *PlanUpdateOne) ClearPurchaseQrURL() *PlanUpdateOne {
	_u.mutation.ClearPurchaseQrURL()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PlanUpdateOne) SetEnabled(v bool) *PlanUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableEnabled(v *bool) *PlanUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *PlanUpdateOne) SetSortOrder(v int) *PlanUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableSortOrder(v *int) *PlanUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *PlanUpdateOne) AddSortOrder(v int) *PlanUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlanUpdateOne) SetUpdatedAt(v time.Time) *PlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PlanMutation object of the builder.
func (_u *PlanUpdateOne) Mutation() *PlanMutation {
	return _u.mutation
}

// Where appends a list predicates to the PlanUpdate builder.
func (_u *PlanUpdateOne) Where(ps ...predicate.Plan) *PlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlanUpdateOne) Select(field string, fields ...string) *PlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Plan entity.
func (_u *PlanUpdateOne) Save(ctx context.Context) (*Plan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlanUpdateOne) SaveX(ctx context.Context) *Plan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := plan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlanUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := plan.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Plan.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupName(); ok {
		if err := plan.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "Plan.group_name": %w`, err)}
		}
	}
	return nil
}

func (_u *PlanUpdateOne) sqlSave(ctx context.Context) (_node *Plan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plan.Table, plan.Columns, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Plan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, plan.FieldID)
		for _, f := range fields {
			if !plan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != plan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(plan.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(plan.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(plan.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(plan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(plan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(plan.FieldGroupName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupSort(); ok {
		_spec.SetField(plan.FieldGroupSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGroupSort(); ok {
		_spec.AddField(plan.FieldGroupSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DailyQuota(); ok {
		_spec.SetField(plan.FieldDailyQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyQuota(); ok {
		_spec.AddField(plan.FieldDailyQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalQuota(); ok {
		_spec.SetField(plan.FieldTotalQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalQuota(); ok {
		_spec.AddField(plan.FieldTotalQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PurchaseQrURL(); ok {
		_spec.SetField(plan.FieldPurchaseQrURL, field.TypeString, value)
	}
	if _u.mutation.PurchaseQrURLCleared() {
		_spec.ClearField(plan.FieldPurchaseQrURL, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(plan.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(plan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(plan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(plan.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Plan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
