// Code generated by ent, DO NOT EDIT.

package invitelog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldLTE(FieldID, id))
}

// InviteID applies equality check predicate on the "invite_id" field. It's identical to InviteIDEQ.
func InviteID(v int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEQ(FieldInviteID, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEQ(FieldAction, v))
}

// InviterID applies equality check predicate on the "inviter_id" field. It's identical to InviterIDEQ.
func InviterID(v int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEQ(FieldInviterID, v))
}

// InviteeID applies equality check predicate on the "invitee_id" field. It's identical to InviteeIDEQ.
func InviteeID(v int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEQ(FieldInviteeID, v))
}

// AdminID applies equality check predicate on the "admin_id" field. It's identical to AdminIDEQ.
func AdminID(v int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEQ(FieldAdminID, v))
}

// RewardAmount applies equality check predicate on the "reward_amount" field. It's identical to RewardAmountEQ.
func RewardAmount(v float64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEQ(FieldRewardAmount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEQ(FieldCreatedAt, v))
}

// InviteIDEQ applies the EQ predicate on the "invite_id" field.
func InviteIDEQ(v int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEQ(FieldInviteID, v))
}

// InviteIDNEQ applies the NEQ predicate on the "invite_id" field.
func InviteIDNEQ(v int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNEQ(FieldInviteID, v))
}

// InviteIDIn applies the In predicate on the "invite_id" field.
func InviteIDIn(vs ...int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldIn(FieldInviteID, vs...))
}

// InviteIDNotIn applies the NotIn predicate on the "invite_id" field.
func InviteIDNotIn(vs ...int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNotIn(FieldInviteID, vs...))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldContainsFold(FieldAction, v))
}

// InviterIDEQ applies the EQ predicate on the "inviter_id" field.
func InviterIDEQ(v int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEQ(FieldInviterID, v))
}

// InviterIDNEQ applies the NEQ predicate on the "inviter_id" field.
func InviterIDNEQ(v int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNEQ(FieldInviterID, v))
}

// InviterIDIn applies the In predicate on the "inviter_id" field.
func InviterIDIn(vs ...int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldIn(FieldInviterID, vs...))
}

// InviterIDNotIn applies the NotIn predicate on the "inviter_id" field.
func InviterIDNotIn(vs ...int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNotIn(FieldInviterID, vs...))
}

// InviteeIDEQ applies the EQ predicate on the "invitee_id" field.
func InviteeIDEQ(v int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEQ(FieldInviteeID, v))
}

// InviteeIDNEQ applies the NEQ predicate on the "invitee_id" field.
func InviteeIDNEQ(v int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNEQ(FieldInviteeID, v))
}

// InviteeIDIn applies the In predicate on the "invitee_id" field.
func InviteeIDIn(vs ...int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldIn(FieldInviteeID, vs...))
}

// InviteeIDNotIn applies the NotIn predicate on the "invitee_id" field.
func InviteeIDNotIn(vs ...int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNotIn(FieldInviteeID, vs...))
}

// AdminIDEQ applies the EQ predicate on the "admin_id" field.
func AdminIDEQ(v int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEQ(FieldAdminID, v))
}

// AdminIDNEQ applies the NEQ predicate on the "admin_id" field.
func AdminIDNEQ(v int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNEQ(FieldAdminID, v))
}

// AdminIDIn applies the In predicate on the "admin_id" field.
func AdminIDIn(vs ...int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldIn(FieldAdminID, vs...))
}

// AdminIDNotIn applies the NotIn predicate on the "admin_id" field.
func AdminIDNotIn(vs ...int64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNotIn(FieldAdminID, vs...))
}

// AdminIDIsNil applies the IsNil predicate on the "admin_id" field.
func AdminIDIsNil() predicate.InviteLog {
	return predicate.InviteLog(sql.FieldIsNull(FieldAdminID))
}

// AdminIDNotNil applies the NotNil predicate on the "admin_id" field.
func AdminIDNotNil() predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNotNull(FieldAdminID))
}

// RewardAmountEQ applies the EQ predicate on the "reward_amount" field.
func RewardAmountEQ(v float64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEQ(FieldRewardAmount, v))
}

// RewardAmountNEQ applies the NEQ predicate on the "reward_amount" field.
func RewardAmountNEQ(v float64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNEQ(FieldRewardAmount, v))
}

// RewardAmountIn applies the In predicate on the "reward_amount" field.
func RewardAmountIn(vs ...float64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldIn(FieldRewardAmount, vs...))
}

// RewardAmountNotIn applies the NotIn predicate on the "reward_amount" field.
func RewardAmountNotIn(vs ...float64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNotIn(FieldRewardAmount, vs...))
}

// RewardAmountGT applies the GT predicate on the "reward_amount" field.
func RewardAmountGT(v float64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldGT(FieldRewardAmount, v))
}

// RewardAmountGTE applies the GTE predicate on the "reward_amount" field.
func RewardAmountGTE(v float64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldGTE(FieldRewardAmount, v))
}

// RewardAmountLT applies the LT predicate on the "reward_amount" field.
func RewardAmountLT(v float64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldLT(FieldRewardAmount, v))
}

// RewardAmountLTE applies the LTE predicate on the "reward_amount" field.
func RewardAmountLTE(v float64) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldLTE(FieldRewardAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InviteLog {
	return predicate.InviteLog(sql.FieldLTE(FieldCreatedAt, v))
}

// HasInvite applies the HasEdge predicate on the "invite" edge.
func HasInvite() predicate.InviteLog {
	return predicate.InviteLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InviteTable, InviteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInviteWith applies the HasEdge predicate on the "invite" edge with a given conditions (other predicates).
func HasInviteWith(preds ...predicate.Invitation) predicate.InviteLog {
	return predicate.InviteLog(func(s *sql.Selector) {
		step := newInviteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInviter applies the HasEdge predicate on the "inviter" edge.
func HasInviter() predicate.InviteLog {
	return predicate.InviteLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InviterTable, InviterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInviterWith applies the HasEdge predicate on the "inviter" edge with a given conditions (other predicates).
func HasInviterWith(preds ...predicate.User) predicate.InviteLog {
	return predicate.InviteLog(func(s *sql.Selector) {
		step := newInviterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInvitee applies the HasEdge predicate on the "invitee" edge.
func HasInvitee() predicate.InviteLog {
	return predicate.InviteLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InviteeTable, InviteeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInviteeWith applies the HasEdge predicate on the "invitee" edge with a given conditions (other predicates).
func HasInviteeWith(preds ...predicate.User) predicate.InviteLog {
	return predicate.InviteLog(func(s *sql.Selector) {
		step := newInviteeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAdmin applies the HasEdge predicate on the "admin" edge.
func HasAdmin() predicate.InviteLog {
	return predicate.InviteLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AdminTable, AdminColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAdminWith applies the HasEdge predicate on the "admin" edge with a given conditions (other predicates).
func HasAdminWith(preds ...predicate.User) predicate.InviteLog {
	return predicate.InviteLog(func(s *sql.Selector) {
		step := newAdminStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InviteLog) predicate.InviteLog {
	return predicate.InviteLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InviteLog) predicate.InviteLog {
	return predicate.InviteLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InviteLog) predicate.InviteLog {
	return predicate.InviteLog(sql.NotPredicates(p))
}
