// Code generated by ent, DO NOT EDIT.

package plan

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the plan type in the database.
	Label = "plan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldGroupName holds the string denoting the group_name field in the database.
	FieldGroupName = "group_name"
	// FieldGroupSort holds the string denoting the group_sort field in the database.
	FieldGroupSort = "group_sort"
	// FieldDailyQuota holds the string denoting the daily_quota field in the database.
	FieldDailyQuota = "daily_quota"
	// FieldTotalQuota holds the string denoting the total_quota field in the database.
	FieldTotalQuota = "total_quota"
	// FieldPurchaseQrURL holds the string denoting the purchase_qr_url field in the database.
	FieldPurchaseQrURL = "purchase_qr_url"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the plan in the database.
	Table = "plans"
)

// Columns holds all SQL columns for plan fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldDescription,
	FieldPrice,
	FieldGroupName,
	FieldGroupSort,
	FieldDailyQuota,
	FieldTotalQuota,
	FieldPurchaseQrURL,
	FieldEnabled,
	FieldSortOrder,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultPrice holds the default value on creation for the "price" field.
	DefaultPrice float64
	// DefaultGroupName holds the default value on creation for the "group_name" field.
	DefaultGroupName string
	// GroupNameValidator is a validator for the "group_name" field. It is called by the builders before save.
	GroupNameValidator func(string) error
	// DefaultGroupSort holds the default value on creation for the "group_sort" field.
	DefaultGroupSort int
	// DefaultDailyQuota holds the default value on creation for the "daily_quota" field.
	DefaultDailyQuota float64
	// DefaultTotalQuota holds the default value on creation for the "total_quota" field.
	DefaultTotalQuota float64
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Plan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByGroupName orders the results by the group_name field.
func ByGroupName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupName, opts...).ToFunc()
}

// ByGroupSort orders the results by the group_sort field.
func ByGroupSort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupSort, opts...).ToFunc()
}

// ByDailyQuota orders the results by the daily_quota field.
func ByDailyQuota(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyQuota, opts...).ToFunc()
}

// ByTotalQuota orders the results by the total_quota field.
func ByTotalQuota(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalQuota, opts...).ToFunc()
}

// ByPurchaseQrURL orders the results by the purchase_qr_url field.
func ByPurchaseQrURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurchaseQrURL, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
