// Code generated by ent, DO NOT EDIT.

package plan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldDescription, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPrice, v))
}

// GroupName applies equality check predicate on the "group_name" field. It's identical to GroupNameEQ.
func GroupName(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldGroupName, v))
}

// GroupSort applies equality check predicate on the "group_sort" field. It's identical to GroupSortEQ.
func GroupSort(v int) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldGroupSort, v))
}

// DailyQuota applies equality check predicate on the "daily_quota" field. It's identical to DailyQuotaEQ.
func DailyQuota(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldDailyQuota, v))
}

// TotalQuota applies equality check predicate on the "total_quota" field. It's identical to TotalQuotaEQ.
func TotalQuota(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldTotalQuota, v))
}

// PurchaseQrURL applies equality check predicate on the "purchase_qr_url" field. It's identical to PurchaseQrURLEQ.
func PurchaseQrURL(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPurchaseQrURL, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldEnabled, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Plan {
	return predicate.Plan(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Plan {
	return predicate.Plan(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldDescription, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldPrice, v))
}

// GroupNameEQ applies the EQ predicate on the "group_name" field.
func GroupNameEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldGroupName, v))
}

// GroupNameNEQ applies the NEQ predicate on the "group_name" field.
func GroupNameNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldGroupName, v))
}

// GroupNameIn applies the In predicate on the "group_name" field.
func GroupNameIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldGroupName, vs...))
}

// GroupNameNotIn applies the NotIn predicate on the "group_name" field.
func GroupNameNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldGroupName, vs...))
}

// GroupNameGT applies the GT predicate on the "group_name" field.
func GroupNameGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldGroupName, v))
}

// GroupNameGTE applies the GTE predicate on the "group_name" field.
func GroupNameGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldGroupName, v))
}

// GroupNameLT applies the LT predicate on the "group_name" field.
func GroupNameLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldGroupName, v))
}

// GroupNameLTE applies the LTE predicate on the "group_name" field.
func GroupNameLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldGroupName, v))
}

// GroupNameContains applies the Contains predicate on the "group_name" field.
func GroupNameContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldGroupName, v))
}

// GroupNameHasPrefix applies the HasPrefix predicate on the "group_name" field.
func GroupNameHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldGroupName, v))
}

// GroupNameHasSuffix applies the HasSuffix predicate on the "group_name" field.
func GroupNameHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldGroupName, v))
}

// GroupNameEqualFold applies the EqualFold predicate on the "group_name" field.
func GroupNameEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldGroupName, v))
}

// GroupNameContainsFold applies the ContainsFold predicate on the "group_name" field.
func GroupNameContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldGroupName, v))
}

// GroupSortEQ applies the EQ predicate on the "group_sort" field.
func GroupSortEQ(v int) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldGroupSort, v))
}

// GroupSortNEQ applies the NEQ predicate on the "group_sort" field.
func GroupSortNEQ(v int) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldGroupSort, v))
}

// GroupSortIn applies the In predicate on the "group_sort" field.
func GroupSortIn(vs ...int) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldGroupSort, vs...))
}

// GroupSortNotIn applies the NotIn predicate on the "group_sort" field.
func GroupSortNotIn(vs ...int) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldGroupSort, vs...))
}

// GroupSortGT applies the GT predicate on the "group_sort" field.
func GroupSortGT(v int) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldGroupSort, v))
}

// GroupSortGTE applies the GTE predicate on the "group_sort" field.
func GroupSortGTE(v int) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldGroupSort, v))
}

// GroupSortLT applies the LT predicate on the "group_sort" field.
func GroupSortLT(v int) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldGroupSort, v))
}

// GroupSortLTE applies the LTE predicate on the "group_sort" field.
func GroupSortLTE(v int) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldGroupSort, v))
}

// DailyQuotaEQ applies the EQ predicate on the "daily_quota" field.
func DailyQuotaEQ(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldDailyQuota, v))
}

// DailyQuotaNEQ applies the NEQ predicate on the "daily_quota" field.
func DailyQuotaNEQ(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldDailyQuota, v))
}

// DailyQuotaIn applies the In predicate on the "daily_quota" field.
func DailyQuotaIn(vs ...float64) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldDailyQuota, vs...))
}

// DailyQuotaNotIn applies the NotIn predicate on the "daily_quota" field.
func DailyQuotaNotIn(vs ...float64) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldDailyQuota, vs...))
}

// DailyQuotaGT applies the GT predicate on the "daily_quota" field.
func DailyQuotaGT(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldDailyQuota, v))
}

// DailyQuotaGTE applies the GTE predicate on the "daily_quota" field.
func DailyQuotaGTE(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldDailyQuota, v))
}

// DailyQuotaLT applies the LT predicate on the "daily_quota" field.
func DailyQuotaLT(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldDailyQuota, v))
}

// DailyQuotaLTE applies the LTE predicate on the "daily_quota" field.
func DailyQuotaLTE(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldDailyQuota, v))
}

// TotalQuotaEQ applies the EQ predicate on the "total_quota" field.
func TotalQuotaEQ(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldTotalQuota, v))
}

// TotalQuotaNEQ applies the NEQ predicate on the "total_quota" field.
func TotalQuotaNEQ(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldTotalQuota, v))
}

// TotalQuotaIn applies the In predicate on the "total_quota" field.
func TotalQuotaIn(vs ...float64) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldTotalQuota, vs...))
}

// TotalQuotaNotIn applies the NotIn predicate on the "total_quota" field.
func TotalQuotaNotIn(vs ...float64) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldTotalQuota, vs...))
}

// TotalQuotaGT applies the GT predicate on the "total_quota" field.
func TotalQuotaGT(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldTotalQuota, v))
}

// TotalQuotaGTE applies the GTE predicate on the "total_quota" field.
func TotalQuotaGTE(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldTotalQuota, v))
}

// TotalQuotaLT applies the LT predicate on the "total_quota" field.
func TotalQuotaLT(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldTotalQuota, v))
}

// TotalQuotaLTE applies the LTE predicate on the "total_quota" field.
func TotalQuotaLTE(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldTotalQuota, v))
}

// PurchaseQrURLEQ applies the EQ predicate on the "purchase_qr_url" field.
func PurchaseQrURLEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPurchaseQrURL, v))
}

// PurchaseQrURLNEQ applies the NEQ predicate on the "purchase_qr_url" field.
func PurchaseQrURLNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldPurchaseQrURL, v))
}

// PurchaseQrURLIn applies the In predicate on the "purchase_qr_url" field.
func PurchaseQrURLIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldPurchaseQrURL, vs...))
}

// PurchaseQrURLNotIn applies the NotIn predicate on the "purchase_qr_url" field.
func PurchaseQrURLNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldPurchaseQrURL, vs...))
}

// PurchaseQrURLGT applies the GT predicate on the "purchase_qr_url" field.
func PurchaseQrURLGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldPurchaseQrURL, v))
}

// PurchaseQrURLGTE applies the GTE predicate on the "purchase_qr_url" field.
func PurchaseQrURLGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldPurchaseQrURL, v))
}

// PurchaseQrURLLT applies the LT predicate on the "purchase_qr_url" field.
func PurchaseQrURLLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldPurchaseQrURL, v))
}

// PurchaseQrURLLTE applies the LTE predicate on the "purchase_qr_url" field.
func PurchaseQrURLLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldPurchaseQrURL, v))
}

// PurchaseQrURLContains applies the Contains predicate on the "purchase_qr_url" field.
func PurchaseQrURLContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldPurchaseQrURL, v))
}

// PurchaseQrURLHasPrefix applies the HasPrefix predicate on the "purchase_qr_url" field.
func PurchaseQrURLHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldPurchaseQrURL, v))
}

// PurchaseQrURLHasSuffix applies the HasSuffix predicate on the "purchase_qr_url" field.
func PurchaseQrURLHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldPurchaseQrURL, v))
}

// PurchaseQrURLIsNil applies the IsNil predicate on the "purchase_qr_url" field.
func PurchaseQrURLIsNil() predicate.Plan {
	return predicate.Plan(sql.FieldIsNull(FieldPurchaseQrURL))
}

// PurchaseQrURLNotNil applies the NotNil predicate on the "purchase_qr_url" field.
func PurchaseQrURLNotNil() predicate.Plan {
	return predicate.Plan(sql.FieldNotNull(FieldPurchaseQrURL))
}

// PurchaseQrURLEqualFold applies the EqualFold predicate on the "purchase_qr_url" field.
func PurchaseQrURLEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldPurchaseQrURL, v))
}

// PurchaseQrURLContainsFold applies the ContainsFold predicate on the "purchase_qr_url" field.
func PurchaseQrURLContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldPurchaseQrURL, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldEnabled, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.NotPredicates(p))
}
